# Generated by Django 5.1.4 on 2025-07-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_remove_quiz_question_count_alter_quiz_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
    ]
