# Generated by Django 5.1.4 on 2026-07-28 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_remove_quiz_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'quiz'], name='question_attempt_user_quiz_idx'),
        ),
    ]
