# Generated by Django 5.1.4 on 2026-09-22 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0015_add_kp_upload_mode_visual_generation_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('linked_subject_name', models.CharField(blank=True, help_text="e.g. 'Physics' — for cross-linking with the curriculum", max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Article Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('article_type', models.CharField(choices=[('educational', 'Educational Content'), ('platform', 'Platform / Company')], default='educational', max_length=20)),
                ('summary', models.TextField(help_text='1-3 sentence summary for meta description and article cards')),
                ('body', models.TextField(help_text='Article body in Markdown. Supports KaTeX math.')),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('featured_image_alt', models.CharField(blank=True, max_length=300)),
                ('meta_title', models.CharField(blank=True, help_text='Override title for <title> tag. Falls back to title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Override for meta description. Falls back to summary.', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('linked_learning_unit', models.ForeignKey(blank=True, help_text='The specific LearningUnit, if more granular than Topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='curriculum.learningunit')),
                ('linked_simulation', models.ForeignKey(blank=True, help_text='A VizLearn simulation referenced or embedded in this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='curriculum.simulation')),
                ('linked_topic', models.ForeignKey(blank=True, help_text='The curriculum Topic this article relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='curriculum.topic')),
                ('related_articles', models.ManyToManyField(blank=True, to='knowledge.article')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.articlecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='knowledge.articletag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='knowledge_a_status_333c27_idx'), models.Index(fields=['article_type', 'status'], name='knowledge_a_article_0c9d16_idx')],
            },
        ),
    ]
