# Generated by Django 5.1.4 on 2026-08-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0014_backfill_content_uuid'),
        ('organizations', '0008_school_setup_wizard_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KCSESchoolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mean_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('mean_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_candidates', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_a_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_a_minus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_b_plus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_b_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_b_minus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_c_plus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_c_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_c_minus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_d_plus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_d_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_d_minus_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grade_e_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kcse_results', to='organizations.school')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='KCSESubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('mean_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('candidates', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('school_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='assessments.kcseschoolresult')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
            options={
                'unique_together': {('school_result', 'subject')},
            },
        ),
    ]
