from typing import Tuple, Optional
from .models import VisualSpecification, GeneratedVisual, GenerationFailure

class VisualRenderer:
    """
    Module 4b: Visual Renderer (Deterministic).
    Takes a VisualSpecification from the Reasoner and converts it into a final GeneratedVisual artifact.
    Does not use LLMs. Performs validation and string cleanup.
    """
    
    @staticmethod
    def render(spec: VisualSpecification) -> Tuple[Optional[GeneratedVisual], Optional[GenerationFailure]]:
        try:
            format_type = spec.format.strip().lower()
            code = spec.code.strip()
            
            # Very basic validation and cleanup
            if format_type == "svg":
                if not code.startswith("<svg") or not code.endswith("</svg>"):
                    return None, GenerationFailure(
                        node_id=spec.node_id,
                        reason="SVG code generated by Reasoner was malformed.",
                        confidence=1.0
                    )
            elif format_type == "mermaid":
                # Strip markdown fences if the LLM leaked them despite instructions
                if code.startswith("```"):
                    lines = code.split('\n')
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines and lines[-1].startswith("```"):
                        lines = lines[:-1]
                    code = '\n'.join(lines).strip()
                    
                if not code.startswith("graph ") and not code.startswith("flowchart ") and not code.startswith("sequenceDiagram"):
                     # Some basic sanity check, but mermaid has many types. We'll let it pass if it's not totally empty.
                     if not code:
                        return None, GenerationFailure(
                            node_id=spec.node_id,
                            reason="Mermaid code generated by Reasoner was empty.",
                            confidence=1.0
                        )
            else:
                return None, GenerationFailure(
                    node_id=spec.node_id,
                    reason=f"Unsupported rendering format: {format_type}",
                    confidence=1.0
                )
                
            # If valid, create the artifact
            visual = GeneratedVisual(
                node_id=spec.node_id,
                asset_type=f"generated_{format_type}",
                url=None, # It's raw code, not an external URL
                file_path=None,
                alt_text=spec.alt_text,
                confidence_score=1.0,
                raw_code=code,
                render_format=format_type
            )
            
            return visual, None
            
        except Exception as e:
            return None, GenerationFailure(
                node_id=spec.node_id,
                reason=f"Renderer crashed: {str(e)}",
                confidence=1.0
            )
