"""
VLearn Grade 10 Biology — Topic 10: Animal Gaseous Exchange and Respiration
Production Ingestion Engine (5 Comprehensive Lessons)

Curriculum: CBC (Curriculum ID: 5)
Grade: Grade 10 (Grade ID: 5, Level: 10)
Subject: Biology (Subject ID: 35)
Topic: Animal Gaseous Exchange and Respiration (Topic Order: 10)

Structured into 5 Comprehensive Learning Units & 5 Published Lessons (~48 Concept Cards):
  1. Characteristics and Diversity of Respiratory Surfaces (9 Pages)
  2. Human Gaseous Exchange and Ventilation Mechanics (10 Pages)
  3. Aerobic and Anaerobic Respiration, Exercise, and Oxygen Debt (10 Pages)
  4. Respiratory Substrates, Respiratory Quotient (RQ), and Energy Requirements (10 Pages)
  5. Investigating Respiration and Designing Gaseous-Exchange Models (9 Pages)

Usage:
  ./venv/bin/python curriculum/ingest_grade10_biology_topic10.py [--replace]
"""

import os
import sys
import re
import django
from django.db import transaction

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Nexus_backend.settings")
django.setup()

from curriculum.models import (
    Curriculum, Grade, Subject, Topic, LearningUnit, Lesson, LessonBlock
)

def clean_text(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r'\[(?:\d+|image_\d+|S\d+.*?|[\d,\s]+)\]', '', text)
    text = re.sub(r'\[VISUAL:\s*[^\]]+\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^\$\$.*?\$\$', '', text, flags=re.MULTILINE | re.DOTALL)
    text = re.sub(r'^[ \t]*[•\u2022][ \t]*', '- ', text, flags=re.MULTILINE)
    text = re.sub(r'([^\n])[ \t]+[•\u2022][ \t]+', r'\1\n- ', text)
    text = re.sub(r'[ \t]+', ' ', text)
    return text.strip()

def clean_dict(data):
    if isinstance(data, str):
        return clean_text(data)
    elif isinstance(data, dict):
        return {k: clean_dict(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [clean_dict(item) for item in data]
    return data

def build_topic10_curriculum():
    return [
        # =====================================================================
        # LESSON 10.1: Characteristics and Diversity of Respiratory Surfaces
        # =====================================================================
        {
            "unit_order": 1,
            "unit_name": "Characteristics and Diversity of Respiratory Surfaces",
            "unit_description": "Five physical rules of effective respiratory surfaces, comparative diversity across amoeba, earthworms, insects, bony fish (counter-current flow), amphibians, birds, and mammals.",
            "lesson_title": "Characteristics and Diversity of Respiratory Surfaces",
            "pages": [
                # Page 1: Learning Focus
                [{"type": "learning_goal", "title": "Learning Focus: Respiratory Surfaces Across Animals", "content": {"title": "Learning Focus: Respiratory Surfaces Across Animals", "goals": ["Explain the five general characteristics of effective biological respiratory surfaces.", "Compare the structures and adaptations of respiratory surfaces across unicellular organisms, earthworms, insects, fish, amphibians, birds, and mammals.", "Explain the mechanism of the counter-current flow system in bony fish.", "Safely and ethically observe the structure of gills from a bony fish in a practical setting."]}}],
                # Page 2: Five Rules
                [{"type": "concept", "title": "Five Rules of Effective Respiratory Design", "content": {"heading": "The 5 Universal Rules of Biological Gas Exchange Surfaces", "body": "Regardless of whether an animal lives in water or on land, its respiratory surface must follow five physical design rules to maximize the rate of passive diffusion:\n\n**1. Extreme Thinness:** The surface epithelium must be only one cell thick to minimize the diffusion distance, allowing rapid passage of gases.\n\n**2. Large Surface Area:** The surface must be highly folded, branched, or divided into millions of microscopic compartments (like alveoli or gill filaments) to maximize the volume of gas exchanged per second.\n\n**3. Moist Environment:** The surface must be kept constantly wet because O₂ and CO₂ cannot diffuse as dry molecules — they must first dissolve in a thin film of water to pass through membranes.\n\n**4. Rich Blood Supply (Vascularization):** In multicellular animals, a dense network of blood capillaries must carry absorbed oxygen away and deliver CO₂ waste, maintaining a steep concentration gradient.\n\n**5. Ventilation Mechanism:** An active system (like breathing movements or swimming) must keep fresh air or water moving across the surface, ensuring high O₂ concentration outside and low inside the body."}}],
                # Page 3: Amoeba and Earthworm
                [{"type": "concept", "title": "Unicellular and Annelid Respiratory Surfaces", "content": {"heading": "Gas Exchange in Amoeba and Earthworms", "body": "**A. Unicellular Organisms (Amoeba):**\n- *Respiratory Surface:* The cell membrane itself.\n- *Adaptation:* The extremely large SA:Vol ratio means simple diffusion across the plasma membrane is fast enough. No specialized respiratory organs are required — oxygen diffuses in and CO₂ diffuses out through the same membrane that serves all other transport functions.\n\n**B. Annelids (Earthworms):**\n- *Respiratory Surface:* The moist skin (integument).\n- *Adaptation:* The skin is a thin, vascularized epithelium. Mucus secretion keeps the skin constantly wet, enabling earthworms to absorb oxygen from air spaces in the soil. This is why earthworms die rapidly on dry concrete — without moisture, their skin desiccates and gas exchange stops, suffocating the worm.\n- *Limitation:* This system limits earthworms to moist, damp soil environments. They cannot survive in dry, hot habitats."}}],
                # Page 4: Insects — Tracheal System
                [{"type": "concept", "title": "The Insect Tracheal System", "content": {"heading": "How Insects Breathe Without a Circulatory Oxygen System", "body": "**C. Insects (Grasshoppers / Locusts):**\n*Respiratory Surface:* The walls of fine tubes called **tracheoles**.\n\n**Pathway of Air:**\n1. Air enters through **spiracles** — tiny, valve-guarded pores on each body segment. Valves prevent water loss; hairs filter dust.\n2. Air travels through branching **tracheae** — rigid tubes lined with chitin rings that prevent collapse — growing progressively narrower.\n3. At the finest branches, air reaches the microscopic **tracheoles** whose walls lack chitin.\n4. Oxygen dissolves in the fluid at the ends of tracheoles and diffuses directly into surrounding muscle cells.\n\n**Flight Adaptation:** During flight, high muscular activity removes fluid from tracheole tips by osmosis (lactic acid builds up, drawing water in). This allows air to penetrate further into the tracheoles, speeding up oxygen delivery to active flight muscles.\n\n**Critical insight:** Insects bypass the circulatory system entirely for gas transport — their haemolymph carries NO oxygen. Only the tracheal system delivers O₂ directly to cells."}}],
                # Page 5: Fish Gills and Counter-Current Flow
                [{"type": "concept", "title": "Fish Gills and the Counter-Current Flow System", "content": {"heading": "Bony Fish: The Most Efficient Natural Gas Exchange System", "body": "**D. Bony Fish (e.g., Tilapia):**\n*Respiratory Surface:* Highly folded gill filaments inside the opercular cavity.\n\n**Gill Structure:**\n- Four gill arches on each side of the pharynx.\n- Each arch carries a bony **gill bar** (support), **gill rakers** (protective comb that filters food particles), and two rows of **gill filaments** folded into microscopic **gill lamellae**.\n\n**Counter-Current Flow System:**\n- Water enters the mouth, flows backward over the gills, and exits through the operculum.\n- Blood flows through the gill lamellae capillaries in the **opposite direction** to water flow.\n- This means blood always encounters water that has a slightly higher O₂ concentration than itself along the entire length of the lamella.\n- The concentration gradient is maintained along the entire length → **continuous diffusion** along 100% of the lamella surface.\n- Efficiency: Up to **80% of dissolved oxygen** extracted from water!\n\n**Parallel flow (less efficient):** If water and blood flowed in the same direction, they would rapidly equalize at ~50% O₂ saturation, and diffusion would stop halfway along the lamella, achieving only ~50% extraction."}}],
                # Page 6: Amphibians, Birds, and Mammals
                [{"type": "concept", "title": "Respiratory Surfaces in Amphibians, Birds, and Mammals", "content": {"heading": "Comparative Respiratory Strategies: Frogs, Birds, and Mammals", "body": "**E. Amphibians (Frogs):** Frogs use three distinct respiratory surfaces:\n1. **Cutaneous (Skin) Respiration:** Thin, moist, vascularized skin handles ~60% of oxygen intake at rest — works both in water and on land. Frogs must stay moist to survive!\n2. **Buccal Cavity:** The moist mouth lining contributes to gas exchange at rest, with air drawn in through open nostrils.\n3. **Lungs:** Small elastic sacs used during high activity (positive pressure breathing: floor of mouth pushes air in, since frogs lack a diaphragm).\n\n**F. Birds:**\n- Lungs paired with nine thin-walled **air sacs** (which do NOT perform gas exchange directly).\n- Air sacs act as bellows, forcing air through the lungs in a **one-way, continuous flow** during BOTH inhalation and exhalation.\n- This ensures the lungs are always filled with fresh, oxygenated air — essential for the enormous energy demands of powered flight.\n\n**G. Mammals (Humans):**\n- Gas exchange occurs across millions of microscopic **alveoli** — highly vascularized air sacs providing ~70 m² total surface area (half a tennis court!)."}}],
                # Page 7: Fish Gills Practical
                [{"type": "concept", "title": "Practical: Observation of Bony Fish Gills", "content": {"heading": "Dissection Procedure — Bony Fish Gill Architecture", "body": "**Objective:** Observe the structural components and adaptations of gills from a bony fish.\n\n**Materials:** Fresh Tilapia fish head (or whole fish), dissecting board, scissors, forceps, water bowl, petri dish, and hand lens.\n\n**Procedure:**\n1. Place the Tilapia on the dissecting board. Observe the external gill cover, the **operculum**.\n2. Use scissors to cut away the operculum to expose the red gills inside the opercular cavity.\n3. Use forceps and scissors to carefully cut out one complete **gill arch** from the pharynx.\n4. Place the isolated gill in a petri dish filled with water. Water will cause the delicate filaments to float and spread out, mimicking their natural state.\n5. Use a hand lens to identify:\n   - **Gill Bar (Arch):** The curved bony support bar.\n   - **Gill Rakers:** Comb-like teeth on the concave side — trap food particles and protect filaments.\n   - **Gill Filaments:** Two rows of thin, red, feathery threads on the convex side.\n\n**Expected Results:** Filaments appear bright red from the rich capillary blood supply. Gill rakers point forward into the mouth, preventing swallowed particles from damaging delicate filaments."}}],
                # Page 8: Common Misconception + Key Terms
                [{"type": "key_terms", "title": "Key Terms: Respiratory Surfaces", "content": {"terms": [{"term": "Gaseous Exchange", "definition": "The physical process by which oxygen diffuses into an organism's body and carbon dioxide diffuses out across a respiratory surface."}, {"term": "Respiratory Surface", "definition": "The specific thin membrane barrier where gas exchange occurs between an organism's internal body and the outside environment."}, {"term": "Tracheal System", "definition": "The respiratory network of insects consisting of branching chitin-lined tubes (tracheae → tracheoles) that deliver oxygen gas directly to tissue cells."}, {"term": "Spiracle", "definition": "A tiny, valve-guarded pore on the body segment of an insect through which air enters and exits the tracheal system."}, {"term": "Counter-Current Flow", "definition": "An anatomical arrangement in bony fish where blood flows through gill lamellae in the opposite direction to water flow, maintaining a continuous O₂ concentration gradient along the full lamella length for maximum extraction efficiency (~80%)."}, {"term": "Operculum", "definition": "The bony external cover plate over the gills of a bony fish that protects the delicate gill filaments and helps regulate water flow."}, {"term": "Cutaneous Respiration", "definition": "Gas exchange occurring directly across the moist skin surface, as in earthworms and amphibians (frogs)."}]}}],
                # Page 9: Knowledge Check
                [{"type": "assessment", "title": "Knowledge Check: Respiratory Surfaces", "content": {"question": "During a dry season, a swamp in Kenya dries up, forcing frogs to bury themselves in mud. How does a frog survive respiring under the mud where its lungs cannot perform ventilation?", "options": ["It performs anaerobic respiration exclusively for months.", "It relies entirely on cutaneous respiration across its thin, moist skin, with oxygen diffusing from air pockets in the damp mud directly into its capillary blood.", "It uses its tracheal system to draw air from the surface.", "It stores oxygen in its large bladder."], "correct_index": 1, "explanation": "Cutaneous (skin) respiration in amphibians does not require active chest ventilation. As long as the skin is kept moist by the damp mud, oxygen dissolves in the skin's moisture film and diffuses directly into blood capillaries, sustaining the frog's reduced metabolic needs during dormancy."}}],
            ]
        },

        # =====================================================================
        # LESSON 10.2: Human Gaseous Exchange and Ventilation Mechanics
        # =====================================================================
        {
            "unit_order": 2,
            "unit_name": "Human Gaseous Exchange and Ventilation Mechanics",
            "unit_description": "Anatomy of the human respiratory tract, alveolar structure-function adaptations, pressure-volume mechanics of inhalation and exhalation, composition of inspired vs expired air, and lung capacity volumes.",
            "lesson_title": "Human Gaseous Exchange and Ventilation Mechanics",
            "pages": [
                # Page 1: Learning Focus
                [{"type": "learning_goal", "title": "Learning Focus: Human Breathing Mechanics", "content": {"title": "Learning Focus: Human Breathing Mechanics", "goals": ["Identify and describe the structures of the human respiratory system from nasal cavity to alveoli.", "Explain the physical mechanism of inhalation and exhalation based on pressure-volume changes.", "Relate the microscopic structure of the alveolus to its gas exchange role.", "Compare the composition of inspired and expired air.", "Distinguish between tidal volume, vital capacity, and residual volume."]}}],
                # Page 2: Respiratory Tract Anatomy
                [{"type": "concept", "title": "Anatomy of the Human Respiratory System", "content": {"heading": "From Nasal Cavity to Alveoli — The Complete Airway", "body": "Air travels through a sequential pathway of structures adapted to clean, warm, and moisten it before reaching the delicate alveolar gas exchange membranes:\n\n**1. Nasal Passages:**\n- Lined with mucus-secreting cells that trap dust, bacteria, and pollen.\n- Beating **cilia** sweep dirty mucus up toward the throat to be swallowed.\n- Winding, vascularized passages warm and moisten incoming air before it reaches the lungs.\n\n**2. Trachea (Windpipe):**\n- Kept permanently open by C-shaped **cartilage rings** that prevent it from collapsing when pressure drops during inhalation.\n- Lined with ciliated mucus cells that continue cleaning air as it descends.\n\n**3. Bronchi and Bronchioles:**\n- The trachea branches into two **bronchi** (one per lung).\n- Inside the lungs, bronchi branch into progressively smaller, cartilage-free **bronchioles**.\n\n**4. Alveoli:**\n- Bronchioles terminate in clusters of 300 million microscopic bubble-like sacs called **alveoli**.\n- Total surface area: ~70 m² (equivalent to half a tennis court)."}}],
                # Page 3: Alveolar Structure-Function
                [{"type": "concept", "title": "Alveolar Structure-Function Adaptations", "content": {"heading": "Why Are Alveoli So Perfectly Designed for Gas Exchange?", "body": "**Vast Surface Area:** 300 million alveoli provide ~70 m² of gas exchange surface — ensuring enormous rates of O₂ and CO₂ transfer per breath.\n\n**Ultra-Thin Barrier:** The alveolar wall is composed of a single flat epithelial cell layer. Tightly bound to this is a single-cell-thick capillary endothelial wall. Gases diffuse across only TWO cells to enter the blood — an incredibly short diffusion distance.\n\n**Moist Lining:** The interior is lined with a thin moisture film in which O₂ first dissolves before crossing the membrane. CO₂ dissolves out of blood and evaporates into the air.\n\n**Surfactant Fluid:** Type II alveolar cells secrete phospholipid surfactant molecules that reduce the surface tension of the water lining. This prevents the wet inner surfaces of alveoli from sticking together and collapsing during exhalation — critical for maintaining lung volume.\n\n**Rich Capillary Network:** Each alveolus is wrapped in a dense mesh of pulmonary capillaries, maintaining steep concentration gradients for O₂ (into blood) and CO₂ (out of blood)."}}],
                # Page 4: Inhalation Mechanics
                [{"type": "concept", "title": "Inhalation: The Active Process of Breathing In", "content": {"heading": "How Does Air Get Into the Lungs? Pressure-Volume Mechanics", "body": "Lungs contain NO muscle tissue — they are passive elastic sacs. Their volume changes are driven entirely by surrounding muscles:\n\n**Inhalation (Active Process):**\n1. **External intercostal muscles contract** → rib cage pulled upward and outward.\n2. **Diaphragm muscles contract** → dome-shaped sheet flattens downward.\n3. Both movements together **increase the volume** of the thoracic (chest) cavity.\n4. By Boyle's Law (P₁V₁ = P₂V₂), increased volume → **decreased air pressure** inside thorax.\n5. Lung pressure drops below atmospheric pressure (101 kPa outside vs. lower inside) → a pressure gradient **sucks air in** through the airways.\n\n**The pleural membrane connection:** The lungs are sealed to the chest wall by the moist pleural membranes. This means when the thorax expands, the lungs are physically pulled open with it, expanding their volume and dropping their internal pressure."}}],
                # Page 5: Exhalation Mechanics
                [{"type": "concept", "title": "Exhalation: The Mostly Passive Process of Breathing Out", "content": {"heading": "How Does Air Leave the Lungs? Elastic Recoil and Muscle Relaxation", "body": "**Exhalation (Passive Process at Rest):**\n1. **External intercostal muscles relax** → rib cage falls inward and downward under its own weight.\n2. **Diaphragm muscles relax** → elastic recoil causes it to dome upward into its resting position.\n3. Both movements **decrease the volume** of the thoracic cavity.\n4. By Boyle's Law, decreased volume → **increased air pressure** inside thorax.\n5. Pressure inside the lungs now rises above atmospheric pressure → pressure gradient **forces air out** of the lungs.\n\n**Forced Exhalation (during exercise or coughing):**\nDuring vigorous activity, passive relaxation is insufficient. The **internal intercostal muscles actively contract**, forcibly pulling the rib cage downward and inward, expelling more air faster.\n\n**Key concept:** Air does NOT push its way in during inhalation. The chest expands FIRST, lowering pressure, which then pulls air in. The lungs are sucked open — not blown open."}}],
                # Page 6: Inspired vs Expired Air
                [{"type": "concept", "title": "Comparing Inspired and Expired Air", "content": {"heading": "What Changes When We Breathe? Inspired vs Expired Gas Composition", "body": "Because gas exchange occurs continuously across the alveolar membranes, exhaled air has a significantly different chemical composition from inhaled air:\n\n| Component | Inspired (Inhaled) | Expired (Exhaled) | Biological Reason |\n|:---|:---|:---|:---|\n| **Oxygen (O₂)** | 21% | 16% | O₂ diffuses across alveoli into blood capillaries to supply tissue respiration. |\n| **Carbon Dioxide (CO₂)** | 0.03% | 4.0% | CO₂ (respiratory waste) diffuses out of blood into alveoli to be exhaled. |\n| **Nitrogen (N₂)** | 79% | 79% | Nitrogen is inert and not utilized by human tissues — unchanged. |\n| **Water Vapour** | Variable (often low) | Saturated | Alveolar surfaces are wet — water evaporates into the air spaces. |\n| **Temperature** | Variable | Warm (~37°C) | Air is warmed to body temperature by capillary-rich nasal cavity lining. |\n\n**Note:** Not ALL oxygen is removed from inhaled air. Exhaled air still contains 16% O₂, which is why mouth-to-mouth resuscitation (rescue breathing) is effective — the exhaled air contains enough O₂ to oxygenate an unconscious person's blood."}}],
                # Page 7: Lung Capacity Volumes
                [{"type": "concept", "title": "Understanding Lung Capacity Volumes", "content": {"heading": "Measuring the Lungs: Tidal Volume, Vital Capacity, and Residual Volume", "body": "Lung volumes are measured using a **spirometer** — a device that records volume changes during breathing:\n\n**Tidal Volume (TV) ≈ 500 cm³:**\nThe volume of air exchanged during a single, normal, relaxed breath. At 15 breaths/min, this means ~7,500 cm³ of air ventilated per minute.\n\n**Inspiratory Reserve Volume (IRV) ≈ 2,500–3,000 cm³:**\nThe additional air that can be forcibly inhaled after a normal tidal inhalation (used during exercise or deep breathing).\n\n**Expiratory Reserve Volume (ERV) ≈ 1,000–1,500 cm³:**\nThe additional air that can be forcibly exhaled after a normal tidal exhalation.\n\n**Vital Capacity (VC) ≈ 3,500–5,000 cm³:**\nThe maximum air exchangeable in a single forced breath (TV + IRV + ERV). Athletes and trained singers have higher vital capacities than average due to stronger respiratory muscles.\n\n**Residual Volume (RV) ≈ 1,200 cm³:**\nAir that ALWAYS remains in the lungs even after maximum forced exhalation. Essential to keep alveoli inflated and prevent them from collapsing completely — prevents the alveolar walls from sticking together."}}],
                # Page 8: Misconception
                [{"type": "concept", "title": "Misconception: Lungs Expand Because Air Pushes Them Open", "content": {"heading": "Do Lungs Inflate Like Balloons Being Blown Up?", "body": "**You may think:** When you inhale, the lungs expand because incoming air physically pushes them open like balloons being blown up.\n\n**Actually:** The lungs expand FIRST — THEN air is drawn in. This is a crucial distinction:\n\nThe diaphragm and external intercostal muscles contract, physically expanding the thoracic volume BEFORE any air moves. The lungs are passively pulled open because they are sealed to the chest wall by the moist pleural membranes — they cannot separate from the thoracic wall.\n\nThis volume increase drops the internal pressure below atmospheric pressure. Air then flows in along the pressure gradient — it is SUCKED in, not pushed in.\n\n**Clinical proof:** If the chest wall is punctured (pneumothorax), atmospheric air enters the pleural cavity, equalizing the pressure and destroying the vacuum. Even when the rib cage expands, the lung remains collapsed because there is no pressure differential to pull it open."}}],
                # Page 9: Key Terms
                [{"type": "key_terms", "title": "Key Terms: Human Gaseous Exchange", "content": {"terms": [{"term": "Alveolus (plural: Alveoli)", "definition": "A microscopic, thin-walled, moist, vascularized air sac in the lungs where gas exchange with the blood capillaries occurs."}, {"term": "Diaphragm", "definition": "A dome-shaped sheet of skeletal muscle separating the thoracic cavity from the abdominal cavity; its contraction flattens it, increasing thoracic volume during inhalation."}, {"term": "Intercostal Muscles", "definition": "Paired muscles running between ribs; external intercostals contract to lift the rib cage during inhalation; internal intercostals contract to force the rib cage down during forced exhalation."}, {"term": "Surfactant", "definition": "A phospholipid fluid secreted by Type II alveolar cells that reduces surface tension, preventing alveoli from collapsing during exhalation."}, {"term": "Tidal Volume", "definition": "The volume of air exchanged during a single normal resting breath (~500 cm³)."}, {"term": "Vital Capacity", "definition": "The maximum volume of air that can be exchanged in a single forced breath (TV + IRV + ERV; approximately 3,500–5,000 cm³)."}, {"term": "Residual Volume", "definition": "Air that permanently remains in the lungs even after maximum exhalation (~1,200 cm³), keeping alveoli open and preventing collapse."}]}}],
                # Page 10: Knowledge Check
                [{"type": "assessment", "title": "Knowledge Check: Ventilation Mechanics", "content": {"question": "During an emergency clinical assessment, a doctor observes that a patient who was in a motorcycle accident has a punctured left chest wall, but his left lung itself remains uninjured. However, the patient's left lung has completely collapsed and cannot inflate during inhalation. What physical principle explains this?", "options": ["The trachea has become blocked by a blood clot.", "The pleural cavity has been punctured, letting air in and equalizing the pressure, which destroys the negative-pressure vacuum needed to pull the lung open.", "The patient has lost too much blood to inflate his lungs.", "The surfactant fluid inside the alveoli has dried up instantly."], "correct_index": 1, "explanation": "The lungs are held open by a vacuum inside the sealed pleural cavity. If the chest wall is punctured, atmospheric air enters the pleural space (pneumothorax), destroying this vacuum. Even when the rib cage expands, there is no pressure differential to pull the lung open, so it remains collapsed despite the intact lung tissue."}}],
            ]
        },

        # =====================================================================
        # LESSON 10.3: Aerobic and Anaerobic Respiration, Exercise, and Oxygen Debt
        # =====================================================================
        {
            "unit_order": 3,
            "unit_name": "Aerobic and Anaerobic Respiration, Exercise, and Oxygen Debt",
            "unit_description": "Comparing aerobic and anaerobic cellular respiration pathways, lactic acid production, oxygen debt concept and repayment, and practical investigation of exercise effects on breathing rate.",
            "lesson_title": "Aerobic and Anaerobic Respiration, Exercise, and Oxygen Debt",
            "pages": [
                # Page 1: Learning Focus
                [{"type": "learning_goal", "title": "Learning Focus: Aerobic vs Anaerobic Respiration", "content": {"title": "Learning Focus: Aerobic vs Anaerobic Respiration", "goals": ["Define and compare aerobic and anaerobic cellular respiration pathways in animals.", "Explain the biochemical formation of lactic acid and the concept of oxygen debt.", "Relate ATP energy output to the chemical substrates of respiration.", "Analyze the physiological effects of physical exercise on breathing rate and recovery time."]}}],
                # Page 2: ATP — The Cell's Energy Currency
                [{"type": "concept", "title": "ATP — The Universal Energy Currency of Cells", "content": {"heading": "What Is ATP and Why Does Every Cell Need It?", "body": "**Adenosine Triphosphate (ATP)** is the primary energy currency of all living cells:\n\n- Structure: Adenine base + Ribose sugar + Three phosphate groups\n- Energy is stored in the high-energy bonds between the phosphate groups.\n- When a cell needs energy, it breaks the bond between the second and third phosphate groups:\n  **ATP → ADP + Pᵢ + Energy (released)**\n- This released energy directly powers cellular work: muscle contraction, protein synthesis, active transport, nerve impulse transmission.\n\n**Why must cells continuously regenerate ATP?**\nCells cannot store large quantities of ATP — it must be continuously regenerated from ADP and Pᵢ using the energy released by breaking down food molecules (glucose, fatty acids). The two pathways for regenerating ATP are **aerobic** (with O₂) and **anaerobic** (without O₂) respiration.\n\n**Scale:** A single human cell contains approximately 1 billion ATP molecules, all of which are used and regenerated within 1–3 minutes during activity."}}],
                # Page 3: Aerobic Respiration
                [{"type": "concept", "title": "Aerobic Respiration — Complete Oxidation with Oxygen", "content": {"heading": "Aerobic Respiration: The High-Efficiency Pathway", "body": "**Definition:** The complete chemical breakdown of organic substrates in the presence of oxygen, yielding CO₂, H₂O, and a high amount of ATP.\n\n**Overall Equation:**\n**C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP (2,880 kJ)**\n\n**Location:** Begins in the **cytoplasm** (glycolysis) but is completed inside the **mitochondria** (Krebs cycle and oxidative phosphorylation).\n\n**Key features:**\n- Glucose is completely oxidized — all chemical energy is released.\n- 38 ATP molecules produced per glucose molecule — highly efficient.\n- CO₂ is a waste product exhaled via the lungs.\n- H₂O is produced and can be excreted by the kidneys.\n- Requires a continuous supply of oxygen from the lungs via blood.\n\n**Why mitochondria?** The folded inner membrane (cristae) of mitochondria provides an enormous surface area for the electron transport chain — the final ATP-generating stage of aerobic respiration."}}],
                # Page 4: Anaerobic Respiration in Animals
                [{"type": "concept", "title": "Anaerobic Respiration — Partial Breakdown Without Oxygen", "content": {"heading": "Anaerobic Respiration: The Emergency Pathway", "body": "**Definition:** The partial chemical breakdown of organic substrates in the ABSENCE of oxygen, yielding a small amount of ATP and toxic lactic acid.\n\n**Overall Equation (Animals / Lactate Fermentation):**\n**C₆H₁₂O₆ → 2 Lactic Acid (C₃H₆O₃) + 2 ATP (150 kJ)**\n\n**Location:** Occurs entirely in the **cytoplasm** — does not require mitochondria.\n\n**Key comparisons vs Aerobic:**\n| Feature | Aerobic | Anaerobic |\n|:---|:---|:---|\n| O₂ required? | Yes | No |\n| ATP yield | 38 ATP | 2 ATP |\n| Byproduct | CO₂ + H₂O | Lactic acid |\n| Location | Cytoplasm + Mitochondria | Cytoplasm only |\n| Efficiency | High (95%) | Very low (5%) |\n| Sustainable? | Long-term | Short bursts only |\n\n**In plants/yeast (Alcoholic Fermentation):**\nC₆H₁₂O₆ → 2 Ethanol + 2 CO₂ + 2 ATP\nPlant anaerobic respiration produces ethanol (not lactic acid) — the basis of fermentation industries."}}],
                # Page 5: Oxygen Debt
                [{"type": "concept", "title": "Lactic Acid Buildup and Oxygen Debt", "content": {"heading": "Why Do Your Muscles Burn During Intense Exercise?", "body": "**During Resting or Moderate Activity:**\nMuscle cells have sufficient O₂ supply and respire aerobically, producing steady ATP. No lactic acid accumulates.\n\n**During Vigorous Exercise (e.g., sprinting, digging):**\n1. Oxygen demand of active muscles exceeds the maximum delivery capacity of the heart and lungs.\n2. To maintain ATP production, muscles switch to anaerobic respiration as a supplement.\n3. Lactic acid accumulates continuously in muscle tissues.\n4. Lactic acid lowers muscle pH, denaturing enzymes and causing muscle fatigue, soreness, and painful cramps.\n5. This physiological state is called **Oxygen Debt** — the deficit of oxygen required to fully oxidize all accumulated lactic acid.\n\n**During Recovery (Post-Exercise):**\nEven after stopping, breathing and heart rate remain high. This extended elevated breathing rate is the body **repaying the oxygen debt**:\n- Additional oxygen is carried to the **liver** via the blood.\n- In the liver, oxygen oxidizes the transported lactic acid back to pyruvic acid.\n- Pyruvic acid is then either completely broken down aerobically (→ CO₂ + H₂O) or reconverted to glucose/glycogen for storage."}}],
                # Page 6: Exercise Breathing Rate Practical
                [{"type": "concept", "title": "Practical: Effect of Exercise on Breathing Rate", "content": {"heading": "Investigating Oxygen Debt — Measuring Recovery After Exercise", "body": "**Objective:** Investigate the effect of physical exercise on breathing rate and recovery time.\n\n**Procedure:**\n1. Work in pairs. Student A sits quietly for 5 minutes to establish resting state.\n2. Student B counts Student A's breaths for exactly 1 minute to establish resting breathing rate. Repeat 3 times; calculate average.\n3. Student A performs vigorous exercise (star jumps, running in place, or skipping) for exactly 10 minutes.\n4. Immediately at end of exercise, Student A sits down. Student B records breathing rate per minute.\n5. Student B continues measuring at 1-minute intervals until breathing rate returns to baseline resting level. Record the **recovery time**.\n\n**Expected Results:**\n- Resting breathing rate: ~15–18 breaths/min.\n- Immediately post-exercise: ~40–50 breaths/min.\n- Recovery curve: A gradual, exponential decline toward resting rate over several minutes.\n\n**Conclusion:** The extended period of elevated breathing after exercise demonstrates oxygen debt repayment. A trained athlete returns to resting rate faster due to greater cardiac efficiency and higher mitochondrial density in muscle fibers."}}],
                # Page 7: Misconception — Plants and Anaerobic Respiration
                [{"type": "concept", "title": "Misconception: Only Animals Respire Anaerobically", "content": {"heading": "Do Plants Perform Anaerobic Respiration?", "body": "**You may think:** Plant cells only perform aerobic respiration and never perform anaerobic respiration.\n\n**Actually:** Plant cells perform anaerobic respiration too — but their byproduct is completely different!\n\nWhen plant cells (or yeast) are deprived of oxygen (e.g., waterlogged crop roots, flooded rice paddies), they perform **alcoholic fermentation:**\n**C₆H₁₂O₆ → 2 Ethanol + 2 CO₂ + 2 ATP**\n\n**Key difference from animals:**\n- Animals (muscle cells) → Lactic acid (no CO₂ released)\n- Plants and yeast → Ethanol + CO₂ (CO₂ IS released)\n\n**Real-world application in Kenya:** This is exactly the chemical process exploited by the brewing industry (fermentation of maize, sorghum, or yeast), the baking industry (yeast CO₂ makes dough rise), and biogas production (anaerobic bacteria fermenting organic waste → methane gas).\n\n**Agricultural relevance:** Prolonged waterlogging of maize farms in Kenya can cause anaerobic conditions in the root zone. Ethanol from root anaerobic respiration is toxic to root cells, causing root death and crop failure — a major concern during El Niño flood events."}}],
                # Page 8: Key Terms
                [{"type": "key_terms", "title": "Key Terms: Respiration and Oxygen Debt", "content": {"terms": [{"term": "Adenosine Triphosphate (ATP)", "definition": "The primary energy currency of cells; energy released when the terminal phosphate bond is broken (ATP → ADP + Pᵢ + Energy)."}, {"term": "Aerobic Respiration", "definition": "Complete breakdown of glucose with O₂ in mitochondria: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP."}, {"term": "Anaerobic Respiration", "definition": "Partial breakdown of glucose without O₂ in the cytoplasm: C₆H₁₂O₆ → 2 Lactic Acid + 2 ATP (animals) or 2 Ethanol + 2 CO₂ + 2 ATP (plants/yeast)."}, {"term": "Lactic Acid", "definition": "A toxic organic byproduct of anaerobic respiration in animal muscle cells; accumulation causes muscle fatigue and cramps by lowering pH."}, {"term": "Oxygen Debt", "definition": "The additional volume of oxygen required after intense exercise to completely oxidize accumulated lactic acid in the liver during the recovery phase."}, {"term": "Alcoholic Fermentation", "definition": "Anaerobic respiration in plants and yeast producing ethanol and CO₂; exploited in brewing, baking, and biogas production."}, {"term": "Mitochondria", "definition": "The double-membrane organelle where aerobic respiration is completed; the cristae (folded inner membrane) provide a large surface area for ATP synthesis."}]}}],
                # Page 9: Knowledge Check
                [{"type": "assessment", "title": "Knowledge Check: Oxygen Debt and Recovery", "content": {"question": "An elite long-distance marathon runner and an untrained student both perform a 100-meter sprint. During the recovery period, the athlete's breathing rate returns to resting levels within 2 minutes, while the student continues to pant heavily for 10 minutes. What biological adaptation explains the athlete's rapid recovery?", "options": ["The athlete's muscles do not produce any lactic acid during exercise.", "The athlete has a larger lung capacity and more mitochondria-dense muscle fibers, allowing for faster oxygen intake and rapid oxidation of lactic acid in the liver.", "The athlete's liver is located closer to their heart.", "The athlete performs anaerobic respiration faster."], "correct_index": 1, "explanation": "Physical training increases cardiac efficiency, lung vital capacity, and muscle vascularization and mitochondrial density. This superior oxygen delivery system allows the athlete to meet energy demands aerobically for longer, and during recovery, delivers oxygen to the liver much faster — enabling rapid repayment of the oxygen debt compared to the untrained student."}}],
                # Page 10: Extra — Practical Variables
                [{"type": "concept", "title": "Analyzing Variables in the Exercise Investigation", "content": {"heading": "Scientific Variables and Controls in the Breathing Rate Experiment", "body": "**Controlled Variables (must remain constant for fair results):**\n- The same student (Student A) performs all sessions.\n- The same type and intensity of exercise is performed each time.\n- Room temperature and humidity remain constant.\n- The duration of the exercise period (10 minutes) remains constant.\n- The same observer (Student B) counts breaths using the same method.\n\n**Independent Variable:** The physical state of Student A (resting, during exercise, during recovery).\n\n**Dependent Variable:** The breathing rate (breaths per minute) measured at each time point.\n\n**Sources of Error and Improvements:**\n- Student A may not be fully rested before the experiment → Allow a standard 5-minute rest period.\n- The observer may miscount breaths → Use two independent observers and average their counts, or use a digital spirometer.\n- Student A may anticipate measurement and consciously alter breathing → Use a pulse oximeter instead of visual breath counting.\n\n**Real-World Application:** These physiological measurements are used by sports scientists in Kenya's Athletics Federation to design training programs that optimize oxygen debt repayment speed in middle-distance and long-distance runners."}}],
            ]
        },

        # =====================================================================
        # LESSON 10.4: Respiratory Substrates, Respiratory Quotient (RQ), and Energy Requirements
        # =====================================================================
        {
            "unit_order": 4,
            "unit_name": "Respiratory Substrates, Respiratory Quotient (RQ), and Energy Requirements",
            "unit_description": "Comparing carbohydrates, lipids, and proteins as respiratory substrates, calculating and interpreting the Respiratory Quotient from gas exchange data, and factors influencing daily human energy requirements.",
            "lesson_title": "Respiratory Substrates, Respiratory Quotient (RQ), and Energy Requirements",
            "pages": [
                # Page 1: Learning Focus
                [{"type": "learning_goal", "title": "Learning Focus: Respiratory Substrates and RQ", "content": {"title": "Learning Focus: Respiratory Substrates and RQ", "goals": ["Identify the three primary respiratory substrates and compare their energy values in kJ/g.", "Define the Respiratory Quotient (RQ) and explain its significance in determining active fuel.", "Calculate and interpret the RQ value from gas exchange measurements.", "Identify the factors that influence human daily energy requirements."]}}],
                # Page 2: The Three Respiratory Substrates
                [{"type": "concept", "title": "The Three Respiratory Substrates", "content": {"heading": "Carbohydrates, Lipids, and Proteins: Fuels of Life", "body": "Cells can utilize three major categories of organic compounds to generate ATP, each with different energy yields and metabolic roles:\n\n**1. Carbohydrates (mainly Glucose) — Primary Fuel:**\n- Energy value: **17.0 kJ/g**\n- The preferred and primary respiratory substrate for ALL cells.\n- Highly soluble in blood plasma; rapidly transported and broken down.\n- The ONLY substrate that can be respired anaerobically during oxygen shortage.\n\n**2. Lipids (Fats and Oils) — Long-Term Fuel Reserve:**\n- Energy value: **38.0 kJ/g** — MORE THAN DOUBLE that of carbohydrates!\n- Used as alternative fuel once cellular carbohydrate reserves are depleted.\n- Lipids are highly reduced (rich in C-H bonds, low in O) — require much more O₂ to fully oxidize, releasing more energy per gram.\n- Stored as body fat — an efficient energy reserve for long fasts, hibernation, or migration.\n\n**3. Proteins — Emergency Last Resort:**\n- Energy value: **22.0 kJ/g**\n- Never used under normal nutritional conditions.\n- Only used as a desperate last resort during prolonged starvation or severe wasting disease.\n- Liver deaminates excess amino acids → urea (excreted by kidneys) + keto-acids → enter the respiratory cycle."}}],
                # Page 3: What is the Respiratory Quotient?
                [{"type": "concept", "title": "The Respiratory Quotient (RQ)", "content": {"heading": "Using Gas Exchange Data to Reveal What Cells Are Burning", "body": "Scientists can determine WHICH substrate a cell is actively burning simply by measuring the gases exchanged during respiration:\n\n**Definition:**\n**RQ = Volume of CO₂ produced ÷ Volume of O₂ consumed**\n\n**Why does this work?** Different substrates have different ratios of carbon to hydrogen to oxygen in their molecular formulas. When they are oxidized, they produce different relative volumes of CO₂ and consume different volumes of O₂ — producing a characteristic RQ value.\n\n**Interpreting RQ Values:**\n| Substrate | RQ Value | Interpretation |\n|:---|:---|:---|\n| Carbohydrates | **1.0** | Equal volumes CO₂ produced and O₂ consumed |\n| Proteins | **0.8–0.9** | Slightly less CO₂ produced than O₂ consumed |\n| Lipids | **0.7** | Much less CO₂ produced than O₂ consumed — lipids need more O₂ |\n| Mixed diet | **0.85** | Average of substrates being burned simultaneously |\n| Anaerobic fermentation | **∞ or undefined** | CO₂ produced but zero O₂ consumed (yeast/plant alcoholic fermentation) |"}}],
                # Page 4: Calculating RQ for Carbohydrates
                [{"type": "concept", "title": "Calculating RQ: Carbohydrates (RQ = 1.0)", "content": {"heading": "Step-by-Step RQ Calculation for Glucose Respiration", "body": "**Aerobic Respiration of Glucose:**\nC₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O\n\n**Calculation:**\nRQ = Volume of CO₂ produced ÷ Volume of O₂ consumed\nRQ = 6 volumes CO₂ ÷ 6 volumes O₂\n**RQ = 1.0**\n\n**Interpretation:** An RQ of exactly 1.0 indicates the organism is burning carbohydrates (glucose or starch) as its sole respiratory substrate. This is expected in:\n- Well-nourished organisms after a carbohydrate-rich meal.\n- Seeds germinating on their starch reserves.\n- Athletes in the first minutes of high-intensity exercise.\n\n**RQ for Lipids (e.g., Tripalmitin — a common dietary fat):**\n2 C₅₁H₉₈O₆ + 145 O₂ → 102 CO₂ + 98 H₂O\n\nRQ = 102 CO₂ ÷ 145 O₂\n**RQ = 0.7**\n\nLipids contain far more hydrogen relative to oxygen than carbohydrates, requiring much more O₂ to completely oxidize — producing proportionally less CO₂ — hence the lower RQ of ~0.7."}}],
                # Page 5: Worked RQ Example (Ketogenic Diet)
                [{"type": "concept", "title": "Worked Example: Using RQ to Identify Metabolic Fuel", "content": {"heading": "Clinical RQ Analysis — Identifying the Active Substrate from Gas Data", "body": "**Scenario:** A clinical researcher measures the gas exchange of a patient undergoing a ketogenic diet. A respirometer records:\n- O₂ consumed: 500 cm³\n- CO₂ produced: 350 cm³\n\n**Step 1: Apply the RQ formula:**\nRQ = CO₂ produced ÷ O₂ consumed\nRQ = 350 cm³ ÷ 500 cm³\n**RQ = 0.70**\n\n**Step 2: Interpret:**\nAn RQ of 0.70 matches the characteristic value for LIPID respiration. This confirms that the ketogenic diet has successfully shifted the patient's primary metabolic fuel from carbohydrates to stored body fat.\n\n**Step 3: Implications:**\n- The patient is in ketosis — burning fatty acids as the primary fuel.\n- Higher O₂ demand per unit of energy released (requires more breathing).\n- Weight loss expected as adipose (fat) stores are mobilized.\n\n**Additional worked examples:**\n- If RQ = 1.00 → burning carbohydrates exclusively (e.g., after eating ugali)\n- If RQ = 0.85 → burning a mix of carbohydrates and proteins (e.g., during starvation with glycogen depletion)\n- If RQ > 1.0 (e.g., 1.2) → converting carbohydrates to fat (lipogenesis) — more CO₂ released than O₂ consumed"}}],
                # Page 6: Factors Influencing Energy Requirements
                [{"type": "concept", "title": "Factors Influencing Daily Energy Requirements", "content": {"heading": "Why Do Different People Need Different Daily Energy Intakes?", "body": "Daily calorie (energy) requirements vary significantly between individuals based on multiple biological and lifestyle factors:\n\n**1. Age:**\nGrowing children and adolescents require more energy per kg of body weight to support rapid cell division, tissue growth, and organ development. Elderly individuals have lower Basal Metabolic Rate (BMR) and reduced muscle mass, requiring less energy.\n\n**2. Gender:**\nOn average, adult males have a higher muscle-to-fat ratio than females, resulting in a higher BMR. Muscle tissue consumes more energy at rest than fat tissue.\n\n**3. Occupation / Activity Level:**\nA manual laborer (farmer digging or tea-picker in Kenya's highlands) has significantly higher muscle energy demands compared to an office worker sitting at a desk all day.\n\n**4. Pregnancy and Lactation:**\nPregnant mothers require ~300 additional kcal/day for fetal growth. Lactating mothers require ~500 additional kcal/day to support milk production.\n\n**5. Health Status:**\nFever raises body temperature by 1°C → BMR increases by ~10–13%. Infections, hyperthyroidism, and severe burns dramatically elevate metabolic rate and caloric requirements."}}],
                # Page 7: Misconception — Lipids for Sports
                [{"type": "concept", "title": "Misconception: Lipids Are Best for Sports Performance", "content": {"heading": "Are Lipids Better Than Carbohydrates for Athletic Energy?", "body": "**You may think:** Since lipids contain more than double the energy density of carbohydrates, athletes should eat high-fat diets for maximum performance.\n\n**Actually:** Carbohydrates remain the undisputed best fuel for high-intensity athletic performance:\n\n**Why carbohydrates win for sport:**\n1. Carbohydrates are RAPIDLY broken down — can power a sprint within seconds.\n2. Only carbohydrates can be respired ANAEROBICALLY — providing emergency ATP when O₂ delivery is insufficient during maximum effort.\n3. Lipid metabolism is SLOW and COMPLEX — requires many more enzymatic steps, making them unsuitable for immediate high-power output.\n4. Lipids require MORE O₂ per unit of ATP generated — at peak exercise when O₂ delivery is already limiting, lipids become an impractical fuel.\n\n**The role of lipids in sport:** Lipids are ideal for LOW-INTENSITY, LONG-DURATION activities (e.g., marathon running at a pace where adequate O₂ is continuously available — the 'fat-burning zone' of aerobic exercise).\n\n**Practical implication:** This is why Kenyan marathon runners eat ugali (complex carbohydrate) before races — not a fatty meal. Carbohydrate loading fills muscle glycogen stores for rapid aerobic and anaerobic fuel."}}],
                # Page 8: Key Terms
                [{"type": "key_terms", "title": "Key Terms: Respiratory Substrates and RQ", "content": {"terms": [{"term": "Respiratory Substrate", "definition": "An organic molecule (glucose, fatty acid, or amino acid) that can be broken down during cellular respiration to release ATP energy."}, {"term": "Respiratory Quotient (RQ)", "definition": "The ratio of CO₂ produced to O₂ consumed during respiration; reveals the active substrate being burned (Carbs = 1.0, Protein = 0.8, Lipid = 0.7)."}, {"term": "Deamination", "definition": "The liver process removing the amino group (-NH₂) from excess amino acids, converting them into urea (excreted) and organic keto-acids that enter the respiratory cycle."}, {"term": "Basal Metabolic Rate (BMR)", "definition": "The minimum energy required by the body at complete rest to maintain basic life functions (breathing, circulation, temperature regulation, organ function)."}, {"term": "Glycogen", "definition": "The storage form of glucose in animal liver and muscle cells — rapidly mobilized to restore blood glucose levels during exercise or fasting."}, {"term": "Ketosis", "definition": "A metabolic state where the body primarily burns fatty acids for fuel (RQ ≈ 0.7), producing ketone bodies — characteristic of ketogenic diets or prolonged starvation."}, {"term": "Lipogenesis", "definition": "The metabolic conversion of excess dietary carbohydrates into fat for storage; produces an RQ > 1.0 because more CO₂ is released than O₂ consumed."}]}}],
                # Page 9: Knowledge Check
                [{"type": "assessment", "title": "Knowledge Check: Respiratory Quotient", "content": {"question": "A clinical researcher measures the gas exchange of a patient undergoing a strict ketogenic diet. The respirometer records that the patient consumed 500 cm³ of oxygen and produced 350 cm³ of carbon dioxide in 10 minutes. Calculate the patient's Respiratory Quotient (RQ) and identify their primary metabolic fuel.", "options": ["RQ = 1.43; the patient is performing anaerobic respiration.", "RQ = 1.00; the patient is burning carbohydrates.", "RQ = 0.70; the patient is burning lipids (fats).", "RQ = 0.85; the patient is burning proteins."], "correct_index": 2, "explanation": "RQ = CO₂ produced ÷ O₂ consumed = 350 cm³ ÷ 500 cm³ = 0.70. An RQ value of exactly 0.70 indicates that the patient is burning lipids (fats) as their primary metabolic fuel — the expected outcome of a ketogenic diet that forces the body to utilize stored body fat instead of dietary carbohydrates."}}],
                # Page 10: Extra — RQ in nature
                [{"type": "concept", "title": "RQ Values in Nature and Agriculture", "content": {"heading": "Real-World Applications of Respiratory Quotient in Biology", "body": "**Germinating Seeds:**\nFresh seeds germinating on stored lipid reserves (e.g., castor bean seeds, which store oils rather than starch) have RQ values of approximately 0.7, confirming lipid metabolism.\n\nSeeds germinating on starch reserves (e.g., maize, wheat, rice) have RQ values close to 1.0, confirming carbohydrate combustion.\n\n**Hibernating Animals:**\nBears and other hibernating mammals live entirely on stored body fat during winter. Their RQ drops to approximately 0.7 throughout the hibernation period.\n\n**Fasting Humans:**\nAfter 12–24 hours of fasting (after glycogen stores are depleted), the RQ gradually falls from ~0.85 toward ~0.7 as the body transitions to fat burning.\n\n**Yeast Fermentation (RQ = ∞):**\nIn anaerobic fermentation: C₆H₁₂O₆ → 2 Ethanol + 2 CO₂ + 2 ATP. CO₂ is produced but ZERO O₂ is consumed. RQ = CO₂/O₂ = 2/0 = undefined (approaches infinity). This is why airtight fermentation vessels must have gas relief valves.\n\n**Agricultural Application (Kenya):** Tea farmers in Kericho can monitor the RQ of freshly harvested tea leaves during withering to determine when enzymatic breakdown is occurring — informing the optimal timing of tea processing."}}],
            ]
        },

        # =====================================================================
        # LESSON 10.5: Investigating Respiration and Designing Gaseous-Exchange Models
        # =====================================================================
        {
            "unit_order": 5,
            "unit_name": "Investigating Respiration and Designing Gaseous-Exchange Models",
            "unit_description": "Detecting heat release from germinating seeds, demonstrating CO₂ release using limewater and hydrogencarbonate indicator, understanding respirometer mechanism, constructing a bell-jar ventilation model, and evaluating model limitations.",
            "lesson_title": "Investigating Respiration and Designing Gaseous-Exchange Models",
            "pages": [
                # Page 1: Learning Focus
                [{"type": "learning_goal", "title": "Learning Focus: Respiration Investigations and Models", "content": {"title": "Learning Focus: Respiration Investigations and Models", "goals": ["Explain how to detect heat release during respiration using vacuum flasks containing germinating seeds.", "Describe how to demonstrate carbon dioxide release using limewater and hydrogencarbonate indicator.", "Analyze the design and mechanism of a respirometer for measuring oxygen consumption.", "Design and construct a working bell-jar model of human ventilation.", "Evaluate the limitations of physical models in representing biological systems."]}}],
                # Page 2: Flask Experiment — Heat Release
                [{"type": "concept", "title": "Detecting Heat Release During Respiration", "content": {"heading": "Experiment 1: Proving Respiration Releases Thermal Energy", "body": "**Concept:** Cellular respiration releases energy. Some is captured as ATP; the rest is lost as heat, raising the surrounding temperature.\n\n**Setup (Two Vacuum / Thermos Flasks):**\n- **Flask A:** Fill with actively germinating seeds (e.g., mung beans or peas soaked in water for 24 hrs — actively respiring).\n- **Flask B (Control):** Fill with dead, boiled seeds that have been soaked in disinfectant (to kill any decay bacteria that would otherwise respire and confound results).\n- Invert both flasks, plug with moist cotton wool, and insert a thermometer into the center of each seed mass.\n\n**Observations over 24–48 hours:**\n- **Flask A:** Temperature rises significantly (e.g., from 22°C to 30–34°C) — heat released by aerobic respiration.\n- **Flask B:** Temperature remains at room temperature (no respiration, no heat).\n\n**Conclusion:** Only living, actively respiring organisms release thermal energy. The dead seeds produce no heat, confirming that heat is a byproduct of cellular metabolism, not merely the decomposition of organic matter."}}],
                # Page 3: CO₂ Detection Tests
                [{"type": "concept", "title": "Detecting Carbon Dioxide in Exhaled Breath", "content": {"heading": "Two Chemical Tests for Carbon Dioxide as a Respiratory Product", "body": "**Test 1 — Limewater (Calcium Hydroxide) Test:**\n- Chemical reaction: Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O\n- CaCO₃ is an insoluble white precipitate that makes the solution turn **cloudy/milky**.\n- *Practical setup:* A student uses a straw to blow expired air through a boiling tube of clear limewater. The solution turns milky within seconds, proving CO₂ is present in breath.\n- *Control:* Pumping normal atmospheric air through limewater produces no turbidity (0.03% CO₂ insufficient to cause visible precipitation).\n\n**Test 2 — Hydrogencarbonate Indicator (HCI) Test:**\nA pH-sensitive chemical indicator that changes color based on CO₂ concentration (pH):\n- **Red:** Normal atmospheric CO₂ concentration (0.03%)\n- **Yellow/Orange:** Increased CO₂ (acidic — CO₂ dissolves to form carbonic acid H₂CO₃)\n- **Purple:** Decreased CO₂ (alkaline — CO₂ removed from air)\n\n*Practical:* Seal a respiring organism (e.g., germinating seeds or a locust) inside a container with the indicator. After 30 minutes, the indicator turns from red → **yellow**, confirming CO₂ production during respiration."}}],
                # Page 4: Respirometer Mechanism
                [{"type": "concept", "title": "How a Respirometer Works", "content": {"heading": "The Respirometer: Measuring the Rate of Oxygen Consumption", "body": "A **respirometer** measures the volume of oxygen consumed by a living organism over time by exploiting a simple physical principle:\n\n**Components:**\n- A sealed boiling tube containing active organisms (blowfly larvae, germinating seeds) on a wire gauze platform.\n- Pellets of **Potassium Hydroxide (KOH)** or Soda Lime below the gauze — these are strong bases that chemically absorb CO₂ gas.\n- A narrow **capillary tube** with a small drop of colored manometer fluid connecting the sealed tube to the atmosphere.\n- A millimeter ruler next to the capillary tube.\n\n**Mechanism (Step by Step):**\n1. Organism consumes O₂ from the sealed tube (gas volume decreases).\n2. Organism releases CO₂, but KOH pellets immediately absorb it.\n3. Net result: the volume of air inside the sealed tube decreases (only O₂ removal registered).\n4. This volume decrease creates a pressure drop inside the tube.\n5. Atmospheric pressure then pushes the manometer fluid droplet toward the tube along the capillary.\n6. The distance the droplet travels per minute = the rate of O₂ consumption = respiration rate."}}],
                # Page 5: KOH and the Respirometer Critical Point
                [{"type": "concept", "title": "Why KOH Pellets Are Essential to the Respirometer", "content": {"heading": "The Critical Role of KOH in Making the Respirometer Work", "body": "**The common student misconception:** Students often think the colored droplet moves because CO₂ is being released. This is WRONG.\n\n**The actual mechanism:** The droplet moves ONLY because oxygen is being CONSUMED.\n\n**Why this matters:** Without KOH pellets:\n- The organism consumes O₂ (gas volume decreases).\n- The organism simultaneously releases CO₂ (gas volume increases).\n- If the organism respires carbohydrates (RQ = 1.0), exactly the same volume of CO₂ is produced as O₂ consumed.\n- Net volume change = 0. The colored droplet does NOT MOVE.\n\n**With KOH pellets:**\n- CO₂ is chemically absorbed by KOH as fast as it is produced: 2KOH + CO₂ → K₂CO₃ + H₂O\n- Only the O₂ consumption causes a net volume decrease.\n- The droplet moves measurably toward the tube.\n- Distance moved per minute = rate of O₂ consumption = respiration rate.\n\n**Control tube:** A separate identical tube with dead (boiled) seeds and KOH is set up simultaneously. Any movement of its droplet indicates volume changes due to temperature or atmospheric pressure fluctuations — not respiration."}}],
                # Page 6: Bell-Jar Ventilation Model
                [{"type": "concept", "title": "Constructing the Bell-Jar Breathing Model", "content": {"heading": "Building a Physical Model of Human Ventilation", "body": "**Purpose:** To model the pressure-volume mechanics of inhalation and exhalation using simple materials.\n\n**Materials and Biological Equivalents:**\n- **Glass/plastic Bell Jar** → Thoracic (chest) cavity and rib cage\n- **Y-shaped glass/plastic tube** → Trachea (stem) and two bronchi (forks)\n- **Two rubber balloons (tied to fork ends)** → Left and right lungs\n- **Flexible rubber sheet (stretched across bottom opening)** → Diaphragm\n\n**Assembly:**\n1. Secure the two balloons to the forks of the Y-tube.\n2. Insert the stem of the Y-tube through a rubber stopper plugging the top of the bell jar.\n3. Stretch the flexible rubber sheet tightly across the open bottom and secure it.\n\n**Operation:**\n- **Inhalation simulation:** Pull the rubber sheet DOWNWARD (models diaphragm flattening) → volume inside jar increases → pressure drops → air enters through Y-tube, inflating balloons.\n- **Exhalation simulation:** Release the rubber sheet (it springs upward, models diaphragm relaxing/doming) → volume inside jar decreases → pressure rises → air is expelled, deflating balloons."}}],
                # Page 7: Model Limitations Table
                [{"type": "concept", "title": "Evaluating Limitations of the Bell-Jar Model", "content": {"heading": "What the Bell-Jar Model Cannot Represent About Real Human Breathing", "body": "While the bell-jar model effectively demonstrates pressure-volume dynamics, it has significant anatomical limitations that students must be able to critically evaluate:\n\n| Model Component | Biological Equivalent | Key Limitation |\n|:---|:---|:---|\n| **Y-Tube** | Trachea and bronchi | Smooth glass/plastic; real trachea has C-shaped cartilage rings, cilia, and mucus-secreting cells for cleaning air. |\n| **Rubber Balloons** | Lungs | Hollow air sacs; real lungs are sponge-like with 300 million vascularized alveoli — the actual gas exchange sites. |\n| **Bell Jar** | Rib cage and thoracic cavity | Rigid glass structure; real rib cage is dynamic — ribs actively move upward and outward driven by intercostal muscles during inhalation. |\n| **Rubber Sheet** | Diaphragm | Must be manually pulled; real diaphragm is an involuntary skeletal muscle contracting rhythmically under neural control from the medulla oblongata. |\n| **No pleural membranes modelled** | Pleural cavity vacuum | No representation of the sealed pleural space that allows the lung to be pulled open when the thorax expands. |\n\n**Conclusion:** The model is a useful pedagogical tool but must be accompanied by anatomical diagrams and critical analysis to avoid oversimplification."}}],
                # Page 8: Key Terms
                [{"type": "key_terms", "title": "Key Terms: Respiration Investigations", "content": {"terms": [{"term": "Respirometer", "definition": "An experimental apparatus that measures the rate of respiration by tracking oxygen consumption — the colored manometer droplet moves as O₂ is consumed and CO₂ is absorbed by KOH."}, {"term": "Potassium Hydroxide (KOH) / Soda Lime", "definition": "Strong chemical bases used in respirometers to absorb CO₂ gas (2KOH + CO₂ → K₂CO₃ + H₂O), ensuring only O₂ consumption causes measurable volume changes."}, {"term": "Hydrogencarbonate Indicator", "definition": "A pH-sensitive indicator that turns yellow/orange when CO₂ increases (acidic), red at normal atmospheric levels, and purple when CO₂ is removed (alkaline)."}, {"term": "Limewater", "definition": "Calcium hydroxide solution — turns milky/cloudy when CO₂ is bubbled through it, forming insoluble white CaCO₃ precipitate."}, {"term": "Manometer Fluid", "definition": "The colored liquid droplet inside the respirometer capillary tube whose movement is measured to calculate the rate of O₂ consumption."}, {"term": "Bell-Jar Model", "definition": "A physical classroom model using a bell jar, Y-tube, balloons, and rubber sheet to demonstrate the pressure-volume mechanics of human inhalation and exhalation."}, {"term": "Model Limitation", "definition": "An aspect of a physical model that does not accurately represent the corresponding biological structure or process, requiring critical evaluation alongside the model."}]}}],
                # Page 9: Knowledge Check
                [{"type": "assessment", "title": "Knowledge Check: Respirometer Design", "content": {"question": "A student sets up a respirometer with active germinating mung beans. However, they accidentally forget to add the Potassium Hydroxide (KOH) pellets at the bottom of the tube. What will happen to the colored liquid droplet during the experiment?", "options": ["It will move rapidly toward the test tube.", "It will move away from the test tube.", "It will remain completely stationary (assuming the beans are burning carbohydrates with an RQ of 1.0).", "It will turn blue."], "correct_index": 2, "explanation": "Mung beans primarily burn starch/glucose (RQ = 1.0). This means they produce exactly the same volume of CO₂ as they consume O₂. Without KOH to absorb the CO₂, the released CO₂ exactly replaces the consumed O₂ volume inside the tube. The net volume change is zero — the pressure inside the tube does not change — so the manometer droplet remains completely stationary."}}],
            ]
        },
    ]


@transaction.atomic
def ingest_topic10(replace=False):
    print("=" * 70)
    print("VLearn Grade 10 Biology — Topic 10: Animal Gaseous Exchange and Respiration")
    print("Ingestion Engine v1.0")
    print("=" * 70)

    curriculum = Curriculum.objects.get(id=5)
    grade = Grade.objects.get(id=5)
    subject = Subject.objects.get(id=35)

    print(f"Curriculum: {curriculum.name} (ID: {curriculum.id})")
    print(f"Grade: {grade.name} (ID: {grade.id})")
    print(f"Subject: {subject.name} (ID: {subject.id})")

    # Scope isolation guard
    assert subject.grade == grade, "SCOPE ISOLATION ERROR: Subject does not belong to Grade 10!"
    assert "biology" in subject.name.lower(), "SCOPE ISOLATION ERROR: Subject is not Biology!"

    if replace:
        existing = Topic.objects.filter(subject=subject, order=10)
        if existing.exists():
            print(f"Replacing existing Topic 10: {existing.first().name}")
            for topic in existing:
                for unit in LearningUnit.objects.filter(topic=topic):
                    for lesson in Lesson.objects.filter(learning_unit=unit):
                        LessonBlock.objects.filter(lesson=lesson).delete()
                        lesson.delete()
                    unit.delete()
                topic.delete()

    topic, created = Topic.objects.get_or_create(
        subject=subject,
        order=10,
        defaults={"name": "Animal Gaseous Exchange and Respiration"}
    )
    if not created:
        if not replace:
            print(f"Topic 10 already exists (ID: {topic.id}). Use --replace to overwrite.")
            return
        topic.name = "Animal Gaseous Exchange and Respiration"
        topic.save()

    print(f"Topic 10: {topic.name} (ID: {topic.id}) — {'created' if created else 'updated'}")

    curriculum_data = build_topic10_curriculum()
    total_lessons = 0
    total_cards = 0
    total_blocks = 0

    for unit_data in curriculum_data:
        unit = LearningUnit.objects.create(
            topic=topic,
            order=unit_data["unit_order"],
            name=unit_data["unit_name"],
            description=unit_data["unit_description"],
        )
        print(f"\n  Unit {unit_data['unit_order']}: {unit.name} (ID: {unit.id})")

        lesson = Lesson.objects.create(
            learning_unit=unit,
            topic=topic,
            title=unit_data["lesson_title"],
            status="published",
        )
        total_lessons += 1
        print(f"    Lesson: {lesson.title} (ID: {lesson.id})")

        pages = unit_data["pages"]
        for page_index, page_blocks in enumerate(pages, start=1):
            for block_data in page_blocks:
                content = clean_dict(block_data.get("content", {}))
                LessonBlock.objects.create(
                    lesson=lesson,
                    page_number=page_index,
                    block_type=block_data["type"],
                    title=clean_text(block_data.get("title", "")),
                    content=content,
                    order=1,
                )
                total_blocks += 1
            total_cards += 1

        print(f"    Pages (Concept Cards): {len(pages)} | Blocks: {sum(len(p) for p in pages)}")

    print("\n" + "=" * 70)
    print("INGESTION COMPLETE")
    print(f"Topic 10: Animal Gaseous Exchange and Respiration — ID: {topic.id}")
    print(f"Total Lessons Ingested: {total_lessons}")
    print(f"Total Concept Cards (Pages): {total_cards}")
    print(f"Total LessonBlocks: {total_blocks}")
    print("=" * 70)


if __name__ == "__main__":
    import sys
    replace = "--replace" in sys.argv
    ingest_topic10(replace=replace)
