# Generated by Django 5.1.4 on 2026-07-28 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_migrate_user_organization_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['school', 'state'], name='org_membership_school_stat_idx'),
        ),
    ]
