# Generated by Django 5.1.4 on 2026-07-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmembership_org_membership_school_stat_idx'),
        ('subscriptions', '0004_product_subscription_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_subscriptions', to='subscriptions.productvariant'),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.school'),
        ),
    ]
