# Generated by Django 5.1.4 on 2026-07-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0004_alter_invoice_user_from_alter_invoice_user_to_and_more'),
        ('curriculum', '0010_simulation'),
        ('organizations', '0004_schoolsubscription_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_subscriptions', to='organizations.academicyear'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='covered_streams',
            field=models.ManyToManyField(blank=True, related_name='school_subscriptions', to='organizations.stream'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='covered_subjects',
            field=models.ManyToManyField(blank=True, related_name='school_subscriptions', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subscription', to='billing_payment.invoice'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='stream_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='term_name',
            field=models.CharField(default='Term 1', max_length=50),
        ),
    ]
