# Generated by Django 5.1.4 on 2026-07-30 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0043_studentsubjectselection_and_more'),
        ('organizations', '0005_schoolsubscription_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='available_devices',
            field=models.JSONField(blank=True, default=list, help_text='List of available device types'),
        ),
        migrations.AddField(
            model_name='school',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_school_setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='curricula_offered',
            field=models.CharField(choices=[('CBC', 'CBC'), ('8-4-4', '8-4-4'), ('BOTH', 'Both CBC and 8-4-4')], default='BOTH', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='electricity_reliability',
            field=models.CharField(choices=[('RELIABLE', 'Reliable'), ('OCCASIONAL_OUTAGES', 'Occasional Outages'), ('FREQUENT_OUTAGES', 'Frequent Outages')], default='RELIABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='estimated_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='estimated_teachers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='internet_access',
            field=models.CharField(choices=[('RELIABLE', 'Reliable'), ('LIMITED', 'Limited'), ('NONE', 'None')], default='LIMITED', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='location_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='location_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='location_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='onboarding_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FAITH_BASED', 'Faith-Based'), ('COMMUNITY', 'Community'), ('NGO', 'NGO'), ('OTHER', 'Other')], default='PUBLIC', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('NATIONAL', 'National School'), ('EXTRA_COUNTY', 'Extra County School'), ('COUNTY', 'County School'), ('SUB_COUNTY', 'Sub County School'), ('PRIVATE', 'Private School'), ('INTERNATIONAL', 'International School'), ('ADULT_LEARNING', 'Adult Learner / Alternative'), ('OTHER', 'Other / Not Sure')], default='PUBLIC', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='setup_draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='setup_status',
            field=models.CharField(choices=[('PROFILE_COMPLETE', 'Profile Complete'), ('STREAMS_CREATED', 'Streams Created'), ('TEACHERS_INVITED', 'Teachers Invited'), ('SUBJECTS_ASSIGNED', 'Subjects Assigned'), ('STUDENTS_IMPORTED', 'Students Imported'), ('BASELINE_UPLOADED', 'Baseline Uploaded'), ('FULLY_CONFIGURED', 'Fully Configured')], default='PROFILE_COMPLETE', max_length=30),
        ),
        migrations.CreateModel(
            name='AcademicExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g., Term 1, Term 2', max_length=50)),
                ('exam_type', models.CharField(choices=[('OPENER', 'Opener Exam'), ('MIDTERM', 'Midterm Exam'), ('ENDTERM', 'End Term Exam'), ('MOCK', 'Mock Exam')], default='ENDTERM', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='organizations.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='organizations.school')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicResultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PROCESSING', 'Processing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='PENDING_REVIEW', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sheets', to='organizations.academicexamination')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_result_sheets', to='Resources.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundProcessingTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('task_type', models.CharField(choices=[('STUDENT_IMPORT', 'Student Roster Import'), ('EXAM_UPLOAD', 'Exam Result Sheet Upload')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedSchoolSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('MERGED', 'Merged'), ('ARCHIVED', 'Archived')], default='UNVERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_schools', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_school_suggestions', to=settings.AUTH_USER_MODEL)),
                ('verified_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_merged', to='organizations.school')),
            ],
        ),
    ]
