# Generated by Django 5.1.4 on 2026-08-22 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_backfill_content_uuid'),
        ('organizations', '0007_alter_school_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='setup_wizard_step',
            field=models.PositiveIntegerField(default=0, help_text='Current step in the setup wizard (0=not started, 1-8=step number)'),
        ),
        migrations.AddField(
            model_name='schoolinvitation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS-based invitations', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveIntegerField()),
                ('exam_count', models.PositiveIntegerField(default=3)),
                ('exam_definitions', models.JSONField(default=list, help_text='List of exam definitions: [{"name": "Opening Exam", "sequence": 1}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configurations', to='organizations.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configurations', to='organizations.school')),
            ],
            options={
                'unique_together': {('school', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_specialties', to='organizations.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_teachers', to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teacher specialties',
                'unique_together': {('teacher', 'subject', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='organizations.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='organizations.school')),
            ],
            options={
                'ordering': ['academic_year', 'number'],
                'unique_together': {('school', 'academic_year', 'number')},
            },
        ),
    ]
