# Generated by Django 5.1.4 on 2026-08-24 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_backfill_content_uuid'),
        ('organizations', '0008_school_setup_wizard_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROGRESS', 'In Progress'), ('TAUGHT', 'Taught / Completed')], default='AVAILABLE', max_length=20)),
                ('last_position', models.CharField(blank=True, default='', help_text='e.g. Worked Example 3, Page 2', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text="Teacher's facilitation notes, reflections, or next steps")),
                ('last_taught_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to='curriculum.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to='organizations.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to='organizations.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to='curriculum.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_logs', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-last_taught_at', '-updated_at'],
                'unique_together': {('teacher', 'stream', 'subject', 'topic', 'lesson')},
            },
        ),
    ]
