# Generated by Django 5.1.4 on 2025-06-16 09:17

import django.core.serializers.json
import django.db.models.deletion
import utils.fields
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_from', models.JSONField(default=dict, encoder=utils.utils.PrettyJSONEncoder)),
                ('invoice_to', models.JSONField(default=dict, encoder=utils.utils.PrettyJSONEncoder)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, encoder=utils.utils.PrettyJSONEncoder, null=True)),
                ('issued_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('BUY_GOODS', 'Buy Goods')], max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('authentication_credentials', utils.fields.EncryptedJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='billing_payment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('payment_details', models.JSONField(default=dict, encoder=utils.utils.PrettyJSONEncoder)),
                ('transaction_details', models.JSONField(default=dict, encoder=utils.utils.PrettyJSONEncoder)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='billing_payment.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaApiAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', utils.fields.EncryptedTextField(max_length=255, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('mpesa_payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to='billing_payment.mpesapaymentaccount')),
            ],
        ),
    ]
