# Generated by Django 5.1.4 on 2026-07-28 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0002_invoice_user_from_invoice_user_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user_to', 'status'], name='invoice_user_to_status_idx'),
        ),
    ]
