# Generated by Django 5.1.4 on 2026-08-03 06:43

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0004_alter_invoice_user_from_alter_invoice_user_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedgerEntry',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('PAYMENT', 'Payment Received'), ('REFUND', 'Refund Issued'), ('ADJUSTMENT', 'Manual Adjustment'), ('CHARGEBACK', 'Chargeback / Dispute')], default='PAYMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict, encoder=utils.utils.PrettyJSONEncoder)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing_payment.invoice')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing_payment.invoicepaymenttransaction')),
            ],
            options={
                'verbose_name': 'Financial Ledger Entry',
                'verbose_name_plural': 'Financial Ledger Entries',
                'ordering': ['-posted_at'],
            },
        ),
    ]
