# Generated by Django 5.1.4 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0005_add_financial_ledger_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentaccount',
            name='environment',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox (Daraja Test)'), ('PRODUCTION', 'Production (Live)')], default='SANDBOX', help_text='The Daraja API environment this account targets.', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesapaymentaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one account per environment should be active at a time.'),
        ),
    ]
