"""
curriculum/generation/engines/chemistry/learning_experience.py

Infrastructure for Chemistry Learning Experience generation.

This module provides:
  - LEARNING_EXPERIENCE_TYPES: the canonical vocabulary of instructional steps for Chemistry.
  - LearningExperienceSchema: validates the JSON schema generated by the AI.
  - LearningExperienceTranslator: compatibility layer that converts the new
    Learning Experience Blueprint into VLearn LessonBlock create-kwargs.
"""

from typing import Any
from curriculum.generation.skeleton import ComponentType, SUGGESTED_TO_ASSET_TYPE

# ---------------------------------------------------------------------------
# Chemistry Instructional Step Vocabulary
# ---------------------------------------------------------------------------

class InstructionalStepType:
    """Canonical string constants for Chemistry instructional steps."""
    HOOK = 'hook'
    LEARNING_OBJECTIVE = 'learning_objective'
    CORE_EXPLANATION = 'core_explanation'
    SCIENTIFIC_VISUALIZATION = 'scientific_visualization'
    KENYAN_REAL_WORLD_EXAMPLE = 'kenyan_real_world_example'
    REQUIRED_MEDIA = 'required_media'
    INTERACTIVE_SIMULATION = 'interactive_simulation'
    WORKED_EXAMPLE = 'worked_example'
    MISCONCEPTION = 'misconception'
    KNOWLEDGE_CHECK = 'knowledge_check'
    REFLECTION = 'reflection'
    SUMMARY = 'summary'
    AI_TUTOR_CONTEXT = 'ai_tutor_context'
    COMPLETION_TAKEAWAY = 'completion_takeaway'

    ALL = [
        HOOK, LEARNING_OBJECTIVE, CORE_EXPLANATION, SCIENTIFIC_VISUALIZATION,
        KENYAN_REAL_WORLD_EXAMPLE, REQUIRED_MEDIA, INTERACTIVE_SIMULATION,
        WORKED_EXAMPLE, MISCONCEPTION, KNOWLEDGE_CHECK, REFLECTION,
        SUMMARY, AI_TUTOR_CONTEXT, COMPLETION_TAKEAWAY,
    ]


# Mapping the Learning Experience steps to the legacy VLearn Component Types
STEP_TO_LEGACY_COMPONENT: dict[str, str] = {
    InstructionalStepType.HOOK: ComponentType.DID_YOU_KNOW,
    InstructionalStepType.LEARNING_OBJECTIVE: ComponentType.LEARNING_GOAL,
    InstructionalStepType.CORE_EXPLANATION: ComponentType.CONCEPT_EXPLANATION,
    InstructionalStepType.SCIENTIFIC_VISUALIZATION: ComponentType.SUGGESTED_DIAGRAM,
    InstructionalStepType.KENYAN_REAL_WORLD_EXAMPLE: ComponentType.REAL_WORLD_CONNECTION,
    InstructionalStepType.REQUIRED_MEDIA: ComponentType.SUGGESTED_VIDEO,
    InstructionalStepType.INTERACTIVE_SIMULATION: ComponentType.SUGGESTED_SIMULATION,
    InstructionalStepType.WORKED_EXAMPLE: ComponentType.WORKED_EXAMPLE,
    InstructionalStepType.MISCONCEPTION: ComponentType.COMMON_MISCONCEPTION,
    InstructionalStepType.KNOWLEDGE_CHECK: ComponentType.KNOWLEDGE_CHECK,
    InstructionalStepType.REFLECTION: ComponentType.REFLECTION,
    InstructionalStepType.SUMMARY: ComponentType.SUMMARY,
    InstructionalStepType.AI_TUTOR_CONTEXT: ComponentType.TEACHER_NOTE,
    InstructionalStepType.COMPLETION_TAKEAWAY: ComponentType.KEY_TAKEAWAY,
}


# ---------------------------------------------------------------------------
# Schema validation
# ---------------------------------------------------------------------------

def validate_learning_experience_schema(blueprint: Any) -> list[str]:
    """
    Validates a parsed Learning Experience Blueprint dict from the LLM.
    Returns a list of error strings; an empty list means the blueprint is valid.
    """
    errors: list[str] = []

    if not isinstance(blueprint, dict):
        return ['Blueprint must be a JSON object.']
    
    learning_experiences = blueprint.get('learning_experiences')
    if not learning_experiences or not isinstance(learning_experiences, list):
        errors.append('Blueprint must contain a non-empty "learning_experiences" list.')
        return errors

    for i, exp in enumerate(learning_experiences):
        exp_label = f'Learning Experience {i + 1}'
        if not isinstance(exp, dict):
            errors.append(f'{exp_label}: must be a JSON object.')
            continue

        steps = exp.get('instructional_steps')
        if not steps or not isinstance(steps, list):
            errors.append(f'{exp_label}: must contain a non-empty "instructional_steps" list.')
            continue

        for j, step in enumerate(steps):
            step_label = f'{exp_label} Step {j + 1}'
            if not isinstance(step, dict):
                errors.append(f'{step_label}: must be a JSON object.')
                continue
            
            s_type = step.get('step_purpose')
            if not s_type:
                errors.append(f'{step_label}: missing "step_purpose" field.')
            elif s_type not in InstructionalStepType.ALL:
                errors.append(f'{step_label}: unknown instructional step purpose "{s_type}".')

    return errors


# ---------------------------------------------------------------------------
# Compatibility Layer: Blueprint → LessonBlock kwargs translator
# ---------------------------------------------------------------------------

class LearningExperienceTranslator:
    """
    Converts a validated Learning Experience Blueprint into an ordered list of dicts, 
    each representing the keyword arguments required to create a legacy LessonBlock.

    This ensures the backend can safely persist the lesson and the frontend 
    can render it without knowing about the new AI Schema.
    """

    @staticmethod
    def translate(blueprint: dict) -> list[dict]:
        """
        Parameters
        ----------
        blueprint : dict
            A validated Learning Experience Blueprint as returned by the LLM.

        Returns
        -------
        list[dict]
            Each dict contains legacy fields:
              block_type, title, content, order, page_number, page_title, 
              component_type, component_order, _asset_instruction, _asset_type
        """
        result: list[dict] = []
        global_order = 0

        for exp_idx, exp in enumerate(blueprint.get('learning_experiences', []), start=1):
            exp_title = exp.get('concept_title', f'Concept {exp_idx}')
            steps = exp.get('instructional_steps', [])

            for step_idx, step in enumerate(steps, start=1):
                step_purpose = step.get('step_purpose', InstructionalStepType.CORE_EXPLANATION)
                
                # Compatibility mapping to legacy component vocabulary
                legacy_comp_type = STEP_TO_LEGACY_COMPONENT.get(step_purpose, ComponentType.CONCEPT_EXPLANATION)
                
                # Determine content payload based on step type
                content_text = step.get('content', '')
                designer_brief = step.get('designer_brief', '')
                
                is_suggested = legacy_comp_type in SUGGESTED_TO_ASSET_TYPE.keys()

                # Build the content object
                if step_purpose == InstructionalStepType.KNOWLEDGE_CHECK:
                    # Keep full step dictionary to preserve options, answer, etc.
                    content_payload = step
                elif legacy_comp_type in [
                    ComponentType.SUGGESTED_ACTIVITY, 
                    ComponentType.REPOSITORY_ASSET, 
                    ComponentType.COMMON_MISCONCEPTION, 
                    ComponentType.ANALOGY, 
                    ComponentType.TEACHER_NOTE
                ]:
                    content_payload = step
                else:
                    content_payload = {'text': content_text} if content_text else step

                block_kwargs = {
                    'block_type': legacy_comp_type,
                    'title': step.get('title', step_purpose.replace('_', ' ').title()),
                    'content': content_payload,
                    'order': global_order,
                    
                    # Legacy presentation fields
                    'page_number': exp_idx,
                    'page_title': exp_title if step_idx == 1 else None,
                    'component_type': legacy_comp_type,
                    'component_order': step_idx,
                    
                    # Asset slot instruction for media steps
                    '_asset_instruction': designer_brief or step.get('instruction') if is_suggested else None,
                    '_asset_type': SUGGESTED_TO_ASSET_TYPE.get(legacy_comp_type) if is_suggested else None,
                }

                result.append(block_kwargs)
                global_order += 1

        return result
