# Generated by Django 5.1.4 on 2026-07-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-version']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.AddField(
            model_name='lesson',
            name='immutable_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores generation_job_id, ai_model, prompt_version, knowledge_pack_version, generated_at'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the lesson', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(blank=True, help_text='Unique identifier generated by AI', max_length=100, null=True)),
                ('block_type', models.CharField(help_text='e.g., overview, objective, core_explanation, video_ref', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Stores markdown string, or JSON payload for media references', null=True)),
                ('order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional block-level metadata like search keywords')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='LearningSection',
        ),
    ]
