# Generated by Django 5.1.4 on 2026-07-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_lesson_options_remove_lesson_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_type', models.CharField(choices=[('full_lesson', 'Full Lesson'), ('single_block', 'Single Block')], default='full_lesson', max_length=20)),
                ('target_block_id', models.CharField(blank=True, help_text='Set if generating a single block', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='curriculum.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_url', models.URLField(help_text='URL of the uploaded textbook')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('review', 'Pending Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='processing', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_packs', to='curriculum.subject')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='knowledge_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lessons', to='curriculum.knowledgepack'),
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., Boyle's Law, Charles's Law", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sequence of the learning unit')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_units', to='curriculum.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(help_text='The raw extracted textbook text')),
                ('chunk_type', models.CharField(help_text='e.g., core_text, worked_example, exercise, definition', max_length=50)),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph_index', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional extracted properties')),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='curriculum.lesson')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='curriculum.topic')),
                ('knowledge_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='curriculum.knowledgepack')),
                ('learning_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='curriculum.learningunit')),
            ],
            options={
                'ordering': ['knowledge_pack', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.learningunit'),
        ),
        migrations.CreateModel(
            name='PedagogyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Chemistry Standard Flow', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogy_templates', to='curriculum.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(help_text='e.g., overview, objective, core_explanation', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Sequence of the block in the template')),
                ('system_prompt', models.TextField(help_text='Instructions for the LLM to generate this block')),
                ('validation_schema', models.JSONField(blank=True, default=dict, help_text='Optional JSON schema for validation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='curriculum.pedagogytemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
