# Generated by Django 5.1.4 on 2026-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_generationrule_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepack',
            name='extracted_structure',
            field=models.JSONField(blank=True, default=list, help_text='JSON structure of Topics and Learning Units extracted from the document'),
        ),
        migrations.AddField(
            model_name='knowledgepack',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded textbook file', null=True, upload_to='textbooks/'),
        ),
        migrations.AlterField(
            model_name='knowledgepack',
            name='source_file_url',
            field=models.URLField(blank=True, help_text='URL of the uploaded textbook', null=True),
        ),
    ]
