# Generated by Django 5.1.4 on 2026-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_knowledgepack_extracted_structure_knowledgepack_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='bounding_box',
            field=models.JSONField(blank=True, help_text='Coordinates [x0, y0, x1, y1]', null=True),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='image',
            field=models.ImageField(blank=True, help_text='Extracted image or cropped scanned region', null=True, upload_to='knowledge_assets/'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='OCR confidence score if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='chunk_type',
            field=models.CharField(help_text='e.g., core_text, worked_example, exercise, definition, diagram, table', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='content_text',
            field=models.TextField(blank=True, help_text='The raw extracted textbook text'),
        ),
    ]
