# Generated by Django 5.1.4 on 2026-07-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_knowledgechunk_bounding_box_knowledgechunk_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonblock',
            name='component_order',
            field=models.IntegerField(blank=True, help_text='Position of this component within its page. NULL = legacy V1 block.', null=True),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='component_type',
            field=models.CharField(blank=True, help_text='Fine-grained learning component role. e.g., learning_goal, concept_explanation, worked_example, knowledge_check, summary, transition, callout, real_world_example, suggested_diagram, suggested_video, suggested_image, suggested_simulation, suggested_gif, suggested_external_link.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Which page (1-indexed) this block belongs to. NULL = legacy V1 block.', null=True),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='page_title',
            field=models.CharField(blank=True, help_text='Optional display title for the page this block introduces.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LessonAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('diagram', 'Diagram'), ('video', 'Video'), ('youtube', 'YouTube Video'), ('gif', 'GIF'), ('simulation', 'Simulation / Interactive Widget'), ('external_link', 'External Link'), ('generated', 'AI-Generated Media')], max_length=50)),
                ('source_type', models.CharField(choices=[('knowledge_repository', 'Knowledge Repository'), ('uploaded', 'Admin Uploaded'), ('ai_generated', 'AI Generated'), ('external', 'External URL')], default='external', max_length=50)),
                ('storage_type', models.CharField(choices=[('file', 'File (server / object storage)'), ('url', 'Remote URL'), ('embed', 'Embed Code / iframe src')], default='url', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending — slot created, media not yet attached'), ('attached', 'Attached — media has been provided'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Caption, alt-text, or AI suggestion prompt for this asset slot.', null=True)),
                ('file', models.FileField(blank=True, help_text='For uploaded or AI-generated static files.', null=True, upload_to='lesson_assets/')),
                ('url', models.URLField(blank=True, help_text='For YouTube, External, or CDN-hosted links.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible payload. Examples: {"youtube_id": "abc123", "duration_seconds": 180} or {"admin_instruction": "Upload a diagram of Boyle\'s Law here."}')),
                ('version', models.IntegerField(default=1, help_text='Incremented each time this asset is replaced with a newer file/URL.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocks', models.ManyToManyField(blank=True, help_text='Which LessonBlocks display this asset.', related_name='assets', to='curriculum.lessonblock')),
                ('knowledge_chunk', models.ForeignKey(blank=True, help_text='Link back to the originating textbook chunk, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_assets', to='curriculum.knowledgechunk')),
                ('lesson', models.ForeignKey(help_text='The lesson this asset belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['lesson', 'asset_type', 'created_at'],
            },
        ),
    ]
