# Generated by Django 5.1.4 on 2026-07-17 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_generationjob_generation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='generation_mode',
            field=models.CharField(choices=[('legacy', 'Legacy (V1 block-by-block)'), ('blueprint', 'Instructional Blueprint (V2)'), ('learning_experience_planner', 'Learning Experience Planner (V3 Pedagogical)')], default='legacy', help_text="Controls which generation engine is used. 'legacy' preserves the V1 GenerationRule loop; 'blueprint' uses the Instructional Designer AI; 'learning_experience_planner' uses the V3 Pedagogical Engine.", max_length=50),
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Detailed semantic explanation of the concept')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of semantic keywords')),
                ('page_number_origin', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructional_metadata', models.JSONField(blank=True, default=dict, help_text='Optional metadata (e.g. cognitive_category, conceptual_complexity) used by the Framework Selection Engine')),
                ('knowledge_pack', models.ForeignKey(blank=True, help_text='The ingestion source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_concepts', to='curriculum.knowledgepack')),
                ('learning_unit', models.ForeignKey(help_text='The primary curriculum entity this concept belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curriculum.learningunit')),
                ('origin_chunk', models.ForeignKey(blank=True, help_text='The exact chunk this concept was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_concepts', to='curriculum.knowledgechunk')),
            ],
            options={
                'ordering': ['learning_unit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningExperienceGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('graph_data', models.JSONField(default=dict, help_text='The structured Adaptive Strategy Graph generated by Agent 3.')),
                ('quality_report', models.JSONField(blank=True, default=dict, help_text='The Validation and Quality Engine report (Validation results, Quality score, Optimizations).')),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Metadata tracking the knowledge chunks used to build this graph.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_graphs', to='curriculum.generationjob')),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_experience_graphs', to='curriculum.learningunit')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bloom_taxonomy_level', models.CharField(blank=True, help_text='e.g., Remember, Understand, Apply, Analyze, Evaluate, Create', max_length=50, null=True)),
                ('page_number_origin', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='curriculum.concept')),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='curriculum.learningunit')),
                ('origin_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.knowledgechunk')),
            ],
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='curriculum.learningexperiencegraph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='The false belief or misunderstanding')),
                ('correction', models.TextField(help_text='The factual correction or explanation')),
                ('page_number_origin', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='curriculum.concept')),
                ('origin_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.knowledgechunk')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('prerequisite', 'Is a prerequisite for'), ('part_of', 'Is part of'), ('causes', 'Causes'), ('related_to', 'Is related to')], max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('origin_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.knowledgechunk')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='curriculum.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='curriculum.concept')),
            ],
            options={
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='RuntimeNodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='locked', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('elapsed_time_seconds', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='e.g., hints used, confidence score, raw answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to='curriculum.learningsession')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('session', 'node_id')},
            },
        ),
    ]
