# Generated by Django migration writer for VLearn Simulation subsystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_generationjob_generation_mode_concept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier key (e.g. charles_law)', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('BIOLOGY', 'Biology'), ('MATHEMATICS', 'Mathematics')], default='CHEMISTRY', max_length=50)),
                ('topic', models.CharField(help_text='e.g., Gas Laws, Electrochemistry', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_DEVELOPMENT', 'In Development'), ('PLACEHOLDER', 'Placeholder')], default='PLACEHOLDER', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief pedagogical overview', null=True)),
                ('archetype', models.CharField(help_text='Client-side component identifier', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Initial parameters and telemetry specs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject', 'status', 'title'],
            },
        ),
    ]
