# Generated by Django 5.1.4 on 2026-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='max_priority_subjects',
            field=models.PositiveIntegerField(default=3, help_text='Maximum help priority subjects allowed'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='max_selectable_subjects',
            field=models.PositiveIntegerField(default=8, help_text='Maximum subjects a student can select'),
        ),
        migrations.AddField(
            model_name='grade',
            name='max_priority_subjects_override',
            field=models.PositiveIntegerField(blank=True, help_text='Grade-level override for max priority subjects', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='max_selectable_subjects_override',
            field=models.PositiveIntegerField(blank=True, help_text='Grade-level override for max subjects', null=True),
        ),
    ]
