# Generated by Django 5.1.4 on 2026-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_curriculum_max_priority_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonasset',
            name='url',
            field=models.URLField(blank=True, help_text='For YouTube, External, or CDN-hosted links.', max_length=1000, null=True),
        ),
    ]
