# Generated by Django 5.1.4 on 2026-08-16 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_lessonasset_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPublication',
            fields=[
                ('publication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.JSONField(default=dict, help_text='Curriculum/Grade/Subject scope of this publication.')),
                ('source_host', models.CharField(help_text='Source database host (no credentials).', max_length=255)),
                ('target_host', models.CharField(help_text='Target database host (no credentials).', max_length=255)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('dry_run', 'Dry Run')], max_length=20)),
                ('counts', models.JSONField(default=dict, help_text='Created/updated/unchanged counts per model.')),
                ('errors', models.JSONField(default=list, help_text='Error messages if any.')),
                ('warnings', models.JSONField(default=list, help_text='Warning messages.')),
                ('report_file', models.CharField(blank=True, help_text='Path to the machine-readable JSON report.', max_length=500)),
                ('published_by', models.CharField(help_text='Hostname of the publishing machine.', max_length=255)),
                ('started_at', models.DateTimeField(help_text='When the publication started.')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curriculum Publication',
                'verbose_name_plural': 'Curriculum Publications',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='concept',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='conceptrelationship',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='conceptrelationship',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='generationrule',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='generationrule',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='knowledgepack',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgepack',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='learningexperiencegraph',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='learningexperiencegraph',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='lessonasset',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='lessonasset',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='misconception',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='misconception',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='pedagogytemplate',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='pedagogytemplate',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='subject',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of content fields for publish change detection.', max_length=64),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='Stable cross-database identity for curriculum publishing.', null=True),
        ),
    ]
