# Generated by Django 5.1.4 on 2026-08-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_backfill_content_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepack',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Populated by AI ingestion. Stores the generated topic/unit list, token usage, and any warnings from the TopicModuleGenerationAgent.'),
        ),
        migrations.AddField(
            model_name='knowledgepack',
            name='upload_mode',
            field=models.CharField(choices=[('normal', 'Normal Upload — manual topic/unit setup'), ('ai_ingestion', 'AI Ingestion — auto-generate topic/unit hierarchy')], default='normal', help_text='Whether the upload triggered AI-ingestion or normal manual setup.', max_length=20),
        ),
        migrations.CreateModel(
            name='VisualGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The admin-provided description of the desired visual.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_block', models.ForeignKey(help_text='The block this visual is being generated for.', on_delete=django.db.models.deletion.CASCADE, related_name='visual_jobs', to='curriculum.lessonblock')),
                ('result_asset', models.ForeignKey(blank=True, help_text='The generated LessonAsset once the job completes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_jobs', to='curriculum.lessonasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
