# Generated by Django 5.1.4 on 2026-09-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_add_kp_upload_mode_visual_generation_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_title', models.CharField(blank=True, max_length=255)),
                ('visualization_type', models.CharField(blank=True, help_text='simulation | youtube | video | diagram | teacher_feedback', max_length=50)),
                ('issue_type', models.CharField(choices=[('youtube_unavailable', 'YouTube video does not exist or is unavailable'), ('simulation_broken', 'Simulation is not launching / blank screen'), ('controls_broken', 'Interactive controls or sliders not responding'), ('content_error', 'Incorrect scientific content or diagram'), ('teacher_feedback', 'Teacher pedagogical feedback / suggestion'), ('other', 'Other issue')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualization_issues', to='curriculum.lesson')),
                ('lesson_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualization_issues', to='curriculum.lessonblock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualization_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
