# Generated by Django 5.1.4 on 2025-03-13 12:09

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=255)),
                ('enrolled_courses', models.IntegerField(default=0)),
                ('completed_courses', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
