# Generated by Django 5.1.4 on 2025-03-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointeractions',
            old_name='student',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='videointeractions',
            old_name='video',
            new_name='video_id',
        ),
    ]
