# Generated by Django 5.1.4 on 2025-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_rename_student_videointeractions_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointeractions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='videointeractions',
            name='video_id',
        ),
        migrations.AddField(
            model_name='videointeractions',
            name='video_url',
            field=models.URLField(default=False, max_length=500),
        ),
    ]
