# Generated by Django 5.1.4 on 2025-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_rename_videointeractions_videointeraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
