# Generated by Django 5.1.4 on 2025-01-14 12:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_alter_form1video_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.DeleteModel(
            name='Form1Video',
        ),
        migrations.DeleteModel(
            name='Form2Video',
        ),
        migrations.DeleteModel(
            name='Form3Video',
        ),
        migrations.DeleteModel(
            name='Form4Video',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='Resources.category'),
        ),
    ]
