# Generated by Django 5.1.4 on 2025-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_quiz_duration_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='duration_minutes',
            new_name='time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.TextField(default='beginner'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
