# Generated by Django 5.1.4 on 2025-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0007_videocourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
