# Generated by Django 5.1.4 on 2025-04-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0008_alter_quiz_difficulty_questionattempt_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='student',
            new_name='user',
        ),
    ]
