# Generated by Django 5.1.4 on 2025-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0009_rename_student_questionattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
