# Generated by Django 5.1.4 on 2025-04-04 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0010_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=20),
        ),
    ]
