# Generated by Django 5.1.4 on 2025-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0011_questionattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
