# Generated by Django 5.1.4 on 2025-04-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0017_uploadedfile_remove_mpesapayment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentvideo',
            name='category',
            field=models.CharField(choices=[('Form 3', 'Form 3'), ('Form 4', 'Form 4')], max_length=50, null=True),
        ),
    ]
