# Generated by Django 5.1.4 on 2025-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0018_experimentvideo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='end_time',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
