# Generated by Django 5.1.4 on 2025-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0019_rename_start_time_questionattempt_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentvideo',
            name='video_link',
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
