# Generated by Django 5.1.4 on 2025-05-05 17:00

import Resources.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0019_rename_start_time_questionattempt_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentvideo',
            name='video_link',
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='video',
            field=models.FileField(null=True, storage=Resources.storages_backends.CloudflareR2Storage(), upload_to='tutorials/'),
        ),
    ]
