# Generated by Django 5.1.4 on 2025-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0020_remove_experimentvideo_video_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentvideo',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='experimentvideo',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='experimentvideo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='experimentvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='experimentvideo',
            name='uid',
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='cloudflare_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
