# Generated by Django 5.1.4 on 2025-05-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0021_remove_experimentvideo_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentvideo',
            name='created_at',
        ),
    ]
