# Generated by Django 5.1.4 on 2025-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0022_remove_experimentvideo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentvideo',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
