# Generated by Django 5.1.4 on 2025-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0023_experimentvideo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentvideo',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='category',
            field=models.CharField(choices=[('Term 1', 'Term 2'), ('Term 1', 'Term 1')], max_length=50, null=True),
        ),
    ]
