# Generated by Django 5.1.4 on 2025-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0025_alter_experimentvideo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentvideo',
            name='category',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2')], max_length=50, null=True),
        ),
    ]
