# Generated by Django 5.1.4 on 2025-06-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0028_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
