# Generated by Django 5.1.4 on 2025-06-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0029_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
