# Generated by Django 5.1.4 on 2025-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0030_alter_questionattempt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
