# Generated by Django 5.1.4 on 2025-07-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0031_alter_questionattempt_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='video',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
