# Generated by Django 5.1.4 on 2025-07-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0032_remove_studentanswer_answer_remove_question_quiz_and_more'),
    ]

    operations = [
    ]
