# Generated by Django 5.1.4 on 2025-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0033_auto_20250701_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.AddField(
            model_name='experimentvideo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experimentvideo',
            name='category',
            field=models.CharField(choices=[('Gas Laws', 'Gas Laws'), ('The Mole', 'The Mole'), ('Organic Chemistry 1', 'Organic Chemistry 1'), ('Nitrogen', 'Nitrogen'), ('Sulphur', 'Sulphur'), ('Chlorine', 'Chlorine')], max_length=50, null=True),
        ),
    ]
