# Generated by Django 5.1.4 on 2025-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0034_delete_mpesapayment_experimentvideo_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
