# Generated by Django 5.1.4 on 2025-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0035_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
