# Generated by Django 5.1.4 on 2025-07-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0036_userprofile_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_available',
        ),
    ]
