# Generated by Django 5.1.4 on 2026-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0037_remove_user_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentvideo',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videointeraction',
            name='video_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
