# Generated by Django 5.1.4 on 2026-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0038_alter_experimentvideo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school_admin', 'School Administrator'), ('platform_admin', 'Platform Administrator')], default='student', max_length=20),
        ),
    ]
