# Generated by Django 5.1.4 on 2026-07-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0041_uploadedfile_user_and_more'),
        ('curriculum', '0010_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='curriculum.curriculum'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curriculum_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='curriculum.grade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_subjects',
            field=models.ManyToManyField(blank=True, related_name='selected_by_students', to='curriculum.subject'),
        ),
    ]
