# Generated by Django 5.1.4 on 2026-07-30 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0042_userprofile_curriculum_userprofile_curriculum_grade_and_more'),
        ('organizations', '0005_schoolsubscription_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField(default=False, help_text='Designates if this subject requires support')),
                ('priority_rank', models.PositiveIntegerField(blank=True, help_text='Rank 1, 2, or 3 for priority', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_priority', 'priority_rank', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_aspiration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confidence_level',
            field=models.CharField(choices=[('VERY_CONFIDENT', 'Very Confident'), ('CONFIDENT', 'Confident'), ('AVERAGE', 'Average'), ('NEED_SUPPORT', 'Need More Support')], default='AVERAGE', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_town_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('MINIMUM_COMPLETE', 'Minimum Complete'), ('FULLY_COMPLETE', 'Fully Complete')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_version',
            field=models.IntegerField(default=1, help_text='Version of onboarding completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_device',
            field=models.CharField(choices=[('PERSONAL_PHONE', 'Personal Phone'), ('TABLET', 'Tablet'), ('LAPTOP', 'Laptop'), ('SHARED_FAMILY_COMPUTER', 'Shared Family Computer'), ('PARENT_GUARDIAN_DEVICE', 'Parent / Guardian Device')], default='PERSONAL_PHONE', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_association_type',
            field=models.CharField(choices=[('VERIFIED_ORGANIZATION', 'Verified Organization'), ('UNVERIFIED_SUGGESTION', 'Unverified Suggestion'), ('INDEPENDENT', 'Independent / No Association'), ('NONE', 'None')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_type',
            field=models.CharField(choices=[('NATIONAL', 'National School'), ('EXTRA_COUNTY', 'Extra County School'), ('COUNTY', 'County School'), ('SUB_COUNTY', 'Sub County School'), ('PRIVATE', 'Private School'), ('INTERNATIONAL', 'International School'), ('ADULT_LEARNING', 'Adult Learner / Alternative'), ('OTHER', 'Other / Not Sure')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unverified_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_student_profiles', to='organizations.school'),
        ),
        migrations.CreateModel(
            name='StudentAcademicBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_scheme', models.CharField(choices=[('LETTER_GRADE', 'Letter Grade (A-E)'), ('PERCENTAGE', 'Percentage (0-100%)'), ('CBC_RUBRIC', 'CBC Rubric (EE, ME, AE, BE)')], default='LETTER_GRADE', max_length=20)),
                ('raw_previous_grade', models.CharField(max_length=20)),
                ('normalized_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_grade', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_baselines', to='organizations.academicyear')),
            ],
        ),
    ]
