# Generated by Django 5.1.4 on 2026-07-30 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0043_studentsubjectselection_and_more'),
        ('curriculum', '0011_curriculum_max_priority_subjects_and_more'),
        ('organizations', '0006_school_available_devices_school_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicbaseline',
            name='examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_baselines', to='organizations.academicexamination'),
        ),
        migrations.AddField(
            model_name='studentacademicbaseline',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_baselines', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='studentacademicbaseline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_baselines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectselection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='studentsubjectselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentacademicbaseline',
            unique_together={('user', 'subject', 'academic_year', 'examination')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectselection',
            unique_together={('user', 'subject')},
        ),
    ]
