# Generated by Django 5.1.4 on 2026-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0044_studentacademicbaseline_examination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Student admission number, unique per school', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number for authentication', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tsc_number',
            field=models.CharField(blank=True, help_text='Teacher Service Commission number', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the OTP code', max_length=64)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('verification_token', models.CharField(blank=True, help_text='Token returned after successful verification', max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'is_verified'], name='Resources_o_phone_n_ec8611_idx')],
            },
        ),
    ]
