from typing import Dict, Set

class GraphValidator:
    """
    Validates the structure of the Adaptive Strategy Graph generated by Agent 3.
    
    IMPORTANT: Since the engine now uses sequential execution_order as the primary
    traversal mechanism (not next_nodes), orphan detection is now a WARNING, not an error.
    The engine auto-repairs all next_nodes before calling this validator.
    
    Hard errors (pipeline-blocking):
      - Missing entry_node_id
      - next_nodes references to non-existent node IDs
    
    Warnings (logged, not blocking):
      - Orphan nodes (unreachable from entry_node_id via next_nodes)
      - Branching nodes without criteria
      - Fewer than 6 nodes
    """

    @staticmethod
    def validate(plan_dict: dict) -> list[str]:
        """
        Takes a raw dictionary representation of the LearningExperiencePlan
        and returns a list of issues. Prefixed with 'WARNING:' for non-fatal issues,
        unprefixed for hard errors. An empty list means the graph is valid.
        """
        errors = []
        nodes = plan_dict.get('nodes', [])
        entry_node_id = plan_dict.get('entry_node_id')

        if not nodes:
            return ["Graph has no nodes."]

        node_dict = {n.get('node_id'): n for n in nodes}

        if entry_node_id not in node_dict:
            errors.append(f"Entry node '{entry_node_id}' does not exist.")
            return errors

        # Minimum node count warning
        if len(nodes) < 6:
            errors.append(f"WARNING: Only {len(nodes)} nodes in plan. Minimum recommended is 6.")

        visited = set()

        # DFS to check edge references (not to delete — just to detect broken links)
        def dfs(node_id: str, path: set):
            if node_id not in node_dict:
                errors.append(f"Reference to non-existent node '{node_id}'.")
                return
            visited.add(node_id)
            node = node_dict[node_id]
            next_nodes = node.get('next_nodes', [])
            for next_id in next_nodes:
                if next_id in path:
                    pass  # Intentional cycle (remediation)
                elif next_id not in visited:
                    path.add(next_id)
                    dfs(next_id, path)
                    path.remove(next_id)

        dfs(entry_node_id, {entry_node_id})

        # Check for orphan nodes — WARNING only (engine repairs these)
        all_node_ids = set(node_dict.keys())
        orphans = all_node_ids - visited
        if orphans:
            errors.append(
                f"WARNING: Orphan nodes detected (unreachable via next_nodes): "
                f"{', '.join(sorted(orphans))}. "
                f"These are linked sequentially by the engine via execution_order."
            )

        # Branching logic check — WARNING only
        for n_id, n in node_dict.items():
            next_nodes = n.get('next_nodes', [])
            if len(next_nodes) > 1:
                has_criteria = n.get('success_criteria') or n.get('failure_criteria')
                has_adaptive = n.get('personalization', {}).get('adaptive_questioning') or n.get('personalization', {}).get('remediation_available')
                if not (has_criteria or has_adaptive):
                    errors.append(
                        f"WARNING: Node '{n_id}' branches to {len(next_nodes)} nodes but lacks "
                        f"success/failure criteria or personalization logic."
                    )

        return errors

